# Python Practice Questions - Session 3 (Pandas DataFrame Basics)

## Topics Covered

- DataFrame Creation
- read_csv()
- shape
- dtypes
- index
- columns
- values
- head()
- tail()
- sample()
- info()
- describe()
- isnull()
- duplicated()
- rename()
- sum()
- min()
- max()
- mean()
- median()
- std()
- var()
- Single Column Selection
- Multiple Column Selection
- iloc()

---

# Dataset

Use the following datasets:

- `movies.csv`
- `ipl-matches.csv`

You may also create your own DataFrames wherever required.

---

# Instructions

- Solve all questions in Jupyter Notebook.
- Use meaningful variable names.
- Add comments wherever necessary.
- Use only **Pandas** and **NumPy**.
- Test your program with multiple examples.
- Do not modify the original dataset unless explicitly instructed.

# Question 1 — Creating and Exploring a DataFrame

## Problem Statement

Create the following DataFrame.

| Roll No | Name | Marks | Package |
|---------|------|-------|---------|
|101|Aman|82|6|
|102|Priya|91|10|
|103|Rahul|76|5|
|104|Neha|88|8|
|105|Karan|69|4|

Store it in a variable named `students`.

### Requirements

1. Display the complete DataFrame.
2. Display the shape of the DataFrame.
3. Display all column names.
4. Display the index.
5. Display the underlying NumPy array.
6. Display the data type of every column.
7. Display the first three rows.
8. Display the last two rows.
9. Display any three random rows.

### Example Output

```text
Shape : (5, 4)

Columns

Roll No
Name
Marks
Package

First Three Rows

...

Random Rows

...

In [1]:
import numpy as np
import pandas as pd

In [2]:
students = {
    "Roll No" : [101,102,103,104,105],
    "Name" : ["Aman","Priya","Rahul","Neha","Karan"],
    "Marks" : [82,91,76,88,69],
    "Package" : [6,10,5,8,4]
}

students = pd.DataFrame(students)
students

   Roll No   Name  Marks  Package
0      101   Aman     82        6
1      102  Priya     91       10
2      103  Rahul     76        5
3      104   Neha     88        8
4      105  Karan     69        4

In [3]:
students.shape

(5, 4)

In [4]:
students.columns

Index(['Roll No', 'Name', 'Marks', 'Package'], dtype='str')

In [5]:
students.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
students.values

array([[101, 'Aman', 82, 6],
       [102, 'Priya', 91, 10],
       [103, 'Rahul', 76, 5],
       [104, 'Neha', 88, 8],
       [105, 'Karan', 69, 4]], dtype=object)

In [7]:
students.dtypes

Roll No    int64
Name         str
Marks      int64
Package    int64
dtype: object

In [8]:
students.head(3)

   Roll No   Name  Marks  Package
0      101   Aman     82        6
1      102  Priya     91       10
2      103  Rahul     76        5

In [9]:
students.tail(2)

   Roll No   Name  Marks  Package
3      104   Neha     88        8
4      105  Karan     69        4

In [10]:
students.sample(3)

   Roll No   Name  Marks  Package
2      103  Rahul     76        5
1      102  Priya     91       10
3      104   Neha     88        8

# Question 2 — Dataset Inspection

## Dataset

`movies.csv`

## Problem Statement

Load the dataset into a DataFrame named `movies`.

### Requirements

1. Display complete information about the dataset.
2. Display the statistical summary.
3. Display the total number of rows.
4. Display the total number of columns.
5. Count missing values in every column.
6. Count duplicate rows.
7. Find the column containing the highest number of missing values.

### Example Output

```text
Rows : 1629

Columns : 18

Missing Values

Poster Path      130
Story             20
Tagline         1072

Duplicate Rows : 0
```

In [11]:
movies = pd.read_csv("movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [12]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   str
 1   imdb_id           1629 non-null   str
 2   poster_path       1526 non-null   str
 3   wiki_link         1629 non-null   str
 4   title_y           1629 non-null   str
 5   original_title    1629 non-null   str
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   str
 9   genres            1629 non-null   str
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   str
 13  summary           1629 non-null   str
 14  tagline           557 non-null    str
 15  actors            1624 non-null   str
 16  wins_nominations  707 non-null    str
 17  release_date      1522 non-null   str
dtypes: float64(1), int64(3), str(14)
memory usage: 2.0 MB

In [13]:
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [14]:
movies.shape[0]

1629

In [15]:
movies.shape[1]

18

In [16]:
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [17]:
movies.duplicated().sum()

np.int64(0)

In [18]:
column = movies.isnull().sum().idxmax()
max_missing_count = movies.isnull().sum().max()
print(f"{column} : {max_missing_count}")

tagline : 1072

# Question 3 — Mathematical Analysis of Student Data

## Problem Statement

Using the `students` DataFrame created in Question 1, perform the following operations.

### Requirements

1. Find the sum of every numerical column.
2. Find the minimum value of every numerical column.
3. Find the maximum value of every numerical column.
4. Find the average of every numerical column.
5. Find the median.
6. Find the standard deviation.
7. Find the variance.
8. Calculate the sum of every row using the appropriate axis.

### Example Output

```text
Column-wise Sum

Roll No      515
Marks        406
Package       33

Row-wise Sum

189
203
184
...
```

In [19]:
column_sums = students.sum(numeric_only=True)

print("Column-wise Sum:")
print(column_sums)

Column-wise Sum:
Roll No    515
Marks      406
Package     33
dtype: int64

In [20]:
column_min = students.min(numeric_only=True)
column_min

Roll No    101
Marks       69
Package      4
dtype: int64

In [21]:
column_max = students.max(numeric_only=True)
column_max

Roll No    105
Marks       91
Package     10
dtype: int64

In [22]:
column_mean = students.mean(numeric_only=True)
column_mean

Roll No    103.0
Marks       81.2
Package      6.6
dtype: float64

In [23]:
column_median = students.median(numeric_only=True)
column_median

Roll No    103.0
Marks       82.0
Package      6.0
dtype: float64

In [24]:
column_std = students.std(numeric_only=True)
column_std

Roll No    1.581139
Marks      8.927486
Package    2.408319
dtype: float64

In [25]:
column_var = students.var(numeric_only=True)
column_var

Roll No     2.5
Marks      79.7
Package     5.8
dtype: float64

In [26]:
rows_sum = students.sum(numeric_only=True,axis=1)
rows_sum

0    189
1    203
2    184
3    200
4    178
dtype: int64

# Question 4 — Column Selection Challenge

## Dataset

`ipl-matches.csv`

## Problem Statement

Load the dataset into a DataFrame named `ipl`.

### Part A — Single Column Selection

Display the following columns individually.

1. team1
2. team2
3. venue
4. city
5. winner

Print the data type returned after selecting each column.

---

### Part B — Multiple Column Selection

Display the following combinations.

1. team1, team2
2. team1, team2, winner
3. season, city, venue
4. toss_winner, toss_decision, winner
5. player_of_match, winner, venue

Print the data type returned in each case.

### Example Output

```text
Single Column

Series

----------------

Multiple Columns

DataFrame
```

In [27]:
ipl = pd.read_csv("ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [28]:
ipl["Team1"]

0                 Rajasthan Royals
1      Royal Challengers Bangalore
2      Royal Challengers Bangalore
3                 Rajasthan Royals
4              Sunrisers Hyderabad
                  ...
945          Kolkata Knight Riders
946                 Mumbai Indians
947               Delhi Daredevils
948                Kings XI Punjab
949    Royal Challengers Bangalore
Name: Team1, Length: 950, dtype: str

In [29]:
ipl["Team2"]

0                   Gujarat Titans
1                 Rajasthan Royals
2             Lucknow Super Giants
3                   Gujarat Titans
4                     Punjab Kings
                  ...
945                Deccan Chargers
946    Royal Challengers Bangalore
947               Rajasthan Royals
948            Chennai Super Kings
949          Kolkata Knight Riders
Name: Team2, Length: 950, dtype: str

In [30]:
ipl["Venue"]

0                Narendra Modi Stadium, Ahmedabad
1                Narendra Modi Stadium, Ahmedabad
2                           Eden Gardens, Kolkata
3                           Eden Gardens, Kolkata
4                        Wankhede Stadium, Mumbai
                          ...
945                                  Eden Gardens
946                              Wankhede Stadium
947                              Feroz Shah Kotla
948    Punjab Cricket Association Stadium, Mohali
949                         M Chinnaswamy Stadium
Name: Venue, Length: 950, dtype: str

In [31]:
ipl["City"]

0       Ahmedabad
1       Ahmedabad
2         Kolkata
3         Kolkata
4          Mumbai
          ...
945       Kolkata
946        Mumbai
947         Delhi
948    Chandigarh
949     Bangalore
Name: City, Length: 950, dtype: str

In [32]:
ipl["WinningTeam"]

0                   Gujarat Titans
1                 Rajasthan Royals
2      Royal Challengers Bangalore
3                   Gujarat Titans
4                     Punjab Kings
                  ...
945          Kolkata Knight Riders
946    Royal Challengers Bangalore
947               Delhi Daredevils
948            Chennai Super Kings
949          Kolkata Knight Riders
Name: WinningTeam, Length: 950, dtype: str

In [33]:
ipl[["Team1","Team2"]]

                           Team1                        Team2
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

[950 rows x 2 columns]

In [34]:
ipl[["Team1","Team2","WinningTeam"]]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

In [35]:
ipl[["Season","City","Venue"]]

      Season        City                                       Venue
0       2022   Ahmedabad            Narendra Modi Stadium, Ahmedabad
1       2022   Ahmedabad            Narendra Modi Stadium, Ahmedabad
2       2022     Kolkata                       Eden Gardens, Kolkata
3       2022     Kolkata                       Eden Gardens, Kolkata
4       2022      Mumbai                    Wankhede Stadium, Mumbai
..       ...         ...                                         ...
945  2007/08     Kolkata                                Eden Gardens
946  2007/08      Mumbai                            Wankhede Stadium
947  2007/08       Delhi                            Feroz Shah Kotla
948  2007/08  Chandigarh  Punjab Cricket Association Stadium, Mohali
949  2007/08   Bangalore                       M Chinnaswamy Stadium

[950 rows x 3 columns]

In [36]:
ipl[["TossWinner","TossDecision","WinningTeam"]]

                      TossWinner TossDecision                  WinningTeam
0               Rajasthan Royals          bat               Gujarat Titans
1               Rajasthan Royals        field             Rajasthan Royals
2           Lucknow Super Giants        field  Royal Challengers Bangalore
3                 Gujarat Titans        field               Gujarat Titans
4            Sunrisers Hyderabad          bat                 Punjab Kings
..                           ...          ...                          ...
945              Deccan Chargers          bat        Kolkata Knight Riders
946               Mumbai Indians          bat  Royal Challengers Bangalore
947             Rajasthan Royals          bat             Delhi Daredevils
948          Chennai Super Kings          bat          Chennai Super Kings
949  Royal Challengers Bangalore        field        Kolkata Knight Riders

[950 rows x 3 columns]

In [37]:
ipl[["Player_of_Match","WinningTeam","Venue"]]

,Player_of_Match,WinningTeam,Venue
0,HH Pandya,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad"
1,JC Buttler,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad"
2,RM Patidar,Royal Challengers Bangalore,"Eden Gardens, Kolkata"
3,DA Miller,Gujarat Titans,"Eden Gardens, Kolkata"
4,Harpreet Brar,Punjab Kings,"Wankhede Stadium, Mumbai"
...,...,...,...
945,DJ Hussey,Kolkata Knight Riders,Eden Gardens
946,MV Boucher,Royal Challengers Bangalore,Wankhede Stadium
947,MF Maharoof,Delhi Daredevils,Feroz Shah Kotla
948,MEK Hussey,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali"
949,BB McCullum,Kolkata Knight Riders,M Chinnaswamy Stadium

# Question 5 — Row Selection and Column Renaming

## Dataset

`movies.csv`

## Problem Statement

Load the dataset into a DataFrame named `movies`.

### Part A — Row Selection

Using **iloc**, perform the following operations.

1. Display the first row.
2. Display the last row.
3. Display rows 20 to 30.
4. Display every alternate row from index 0 to 20.
5. Display rows having index positions:
   - 5
   - 15
   - 25
   - 35
6. Display the last 15 rows using negative indexing.

---

### Part B — Rename Columns

Create the following DataFrame.

| ID | Marks | Package |
|----|-------|---------|
|101|80|6|
|102|90|9|
|103|75|5|

Rename the columns as follows.

| Old Name | New Name |
|----------|----------|
|ID|Student_ID|
|Marks|Percentage|
|Package|LPA|

Make the changes permanent.

Display the updated DataFrame and print the updated column names.

### Example Output

```text
Updated Columns

Student_ID
Percentage
LPA

Updated DataFrame

Student_ID   Percentage   LPA
101          80           6
102          90           9
103          75           5
```

In [38]:
movies = pd.read_csv("movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [39]:
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

In [40]:
movies.iloc[-1]

title_x                                                      Humsafar
imdb_id                                                     tt2403201
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link                      https://en.wikipedia.org/wiki/Humsafar
title_y                                                      Humsafar
original_title                                               Humsafar
is_adult                                                            0
year_of_release                                                  2011
runtime                                                            35
genres                                                  Drama|Romance
imdb_rating                                                       9.0
imdb_votes                                                       2968
story               Sara and Ashar are childhood friends who share...
summary             Ashar and Khirad are forced to get married due...
tagline                                                           NaN
actors                                                    Fawad Khan|
wins_nominations                                                  NaN
release_date                                    TV Series (2011–2012)
Name: 1628, dtype: object

In [41]:
movies.iloc[20:31]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
20,Mere Pyare Prime Minister,tt8207768,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Pyare_Prime...,Mere Pyare Prime Minister,Mere Pyare Prime Minister,0,2018,104,Drama,6.8,344,A story about four children living in a Mumbai...,A story about four children living in a Mumbai...,Meri Ek Arzi Sun Lo Zara,Rasika Agashe|Sonia Albizuri|Syna Anand|Adarsh...,NaN,15 March 2019 (India)
21,22 Yards,tt9496212,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/22_Yards,22 Yards,22 Yards,0,2019,126,Sport,5.3,124,A dramatic portrayal of a victorious tale of a...,A dramatic portrayal of a victorious tale of a...,NaN,Barun Sobti|Rajit Kapur|Panchhi Bora|Kartikey ...,NaN,15 March 2019 (India)
22,Kesari (film),tt6264938,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kesari_(film),Kesari,Kesari,0,2019,150,Action|Drama|History,7.4,10653,This period war-drama showcases the 1897 Battl...,Based on an incredible true story of the Battl...,NaN,Akshay Kumar|Parineeti Chopra|Suvinder Vicky|V...,NaN,21 March 2019 (USA)
23,Notebook (2019 film),tt9105014,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Notebook_(2019_f...,Notebook,Notebook,0,2019,115,Drama|Romance,6.8,1335,In the Kashmir valley Kabir a former army offi...,An ex-army officer Kabir becomes a teacher i...,NaN,Zaheer Iqbal|Pranutan Bahl|Mir Mohammed Mehroo...,NaN,29 March 2019 (USA)
24,Junglee (2019 film),tt7463730,https://upload.wikimedia.org/wikipedia/en/e/e2...,https://en.wikipedia.org/wiki/Junglee_(2019_film),Junglee,Junglee,0,2019,115,Action|Adventure,5.3,1064,Dipankar Nair runs a Elephant sanctuary but th...,The story revolves around a vet who on his ho...,NaN,Vidyut Jammwal|Lars Kjeldsen|,NaN,29 March 2019 (USA)
25,Gone Kesh,tt10017956,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gone_Kesh,Gone Kesh,Gone Kesh,0,2019,110,Drama,7.1,178,Enakshi is diagnosed with Alopecia where she ...,Enakshi is diagnosed with Alopecia where she ...,NaN,Deepika Amin|Kumar Kanchan Ghosh|Brijendra Kal...,9 wins,29 March 2019 (India)
26,Albert Pinto Ko Gussa Kyun Aata Hai?,tt4355838,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Albert_Pinto_Ko_...,Albert Pinto Ko Gussa Kyun Aata Hai?,Albert Pinto Ko Gussa Kyun Aata Hai?,0,2019,100,Drama,4.8,56,Albert leaves his house one morning without te...,Albert Pinto goes missing one day and his girl...,NaN,Manav Kaul|Nandita Das|,NaN,12 April 2019 (India)
27,The Tashkent Files,tt8108268,https://upload.wikimedia.org/wikipedia/en/7/79...,https://en.wikipedia.org/wiki/The_Tashkent_Files,The Tashkent Files,The Tashkent Files,0,2019,134,Drama|Mystery|Thriller,8.0,5524,The Tashkent Files is a thriller that revolves...,The Tashkent Files is a thriller that revolves...,NaN,Naseeruddin Shah|Mithun Chakraborty|Shweta Bas...,NaN,12 April 2019 (India)
28,Kalank,tt6988116,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kalank,Kalank,Kalank,0,2019,166,Drama|Romance,3.6,9106,Set in 1945 in Pre-Independent India the eli...,The lives of six enigmatic characters become e...,NaN,Varun Dhawan|Alia Bhatt|Aditya Roy Kapoor|Madh...,NaN,17 April 2019 (USA)
29,Setters (film),tt9239772,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Setters_(film),Setters,Setters,0,2019,126,Thriller,5.1,158,A thriller set in Benares Jaipur Mumbai and ...,A thriller set in Benares Jaipur Mumbai and ...,NaN,Shreyas Talpade|Aftab Shivdasani|Sonnalli Seyg...,NaN,3 May 2019 (India)
30,Student of the Year 2,tt7255568,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Student_of_the_Y...,Student of the Year 2,Student of the Year 2,0,2019,146,Drama|Romance|Sport,2.5,12671,A student must face off against bullies and ov...,A student must face off against bullies and ov...,NaN,Tiger Shroff|Ananya Panday|Tara Sutaria|Aditya...,NaN,10 May 2019 (USA)

In [42]:
movies.iloc[0:21:2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,NaN,18 January 2019 (India)
8,Manikarnika: The Queen of Jhansi,tt6903440,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Manikarnika:_The...,Manikarnika: The Queen of Jhansi,Manikarnika: The Queen of Jhansi,0,2019,148,Action|Biography|Drama,6.5,7361,Manikarnika born in Varanasi when Dixt a minis...,Story of Rani Lakshmibai one of the leading f...,NaN,Kangana Ranaut|Rimi Sen|Atul Kulkarni|Nalneesh...,NaN,25 January 2019 (USA)
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,NaN,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,NaN,8 February 2019 (India)
12,Hum Chaar,tt9319812,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hum_Chaar,Hum chaar,Hum chaar,0,2019,143,Drama,5.6,183,The story of the film revolves around four col...,The story of the film revolves around four col...,NaN,Prit Kamani|Simran Sharma|Anshuman Malhotra|Tu...,NaN,15 February 2019 (India)
14,Sonchiriya,tt8108200,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Sonchiriya,Sonchiriya,Sonchiriya,0,2019,143,Action|Crime|Drama,7.5,2322,This is the story of a group of rebels in Cham...,Set in the Chambal valley the film follows th...,NaN,Sushant Singh Rajput|Bhumi Pednekar|Manoj Bajp...,NaN,1 March 2019 (India)
16,Mard Ko Dard Nahi Hota,tt8055888,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mard_Ko_Dard_Nah...,Mard Ko Dard Nahin Hota,Mard Ko Dard Nahin Hota,0,2018,134,Action|Comedy,7.4,3969,It is a story of a young boy Surya who has a r...,It is a story of a young boy Surya who has a r...,NaN,Abhimanyu Dasani|Radhika Madan|Prateek Parmar|...,2 wins & 2 nominations,22 March 2019 (USA)
18,Photograph (film),tt7778680,https://upload.wikimedia.org/wikipedia/en/7/71...,https://en.wikipedia.org/wiki/Photograph_(film),Photograph,Photograph,0,2019,110,Drama|Romance,6.9,2391,Two lives intersect in Mumbai and go along tog...,A struggling street photographer in Mumbai pr...,NaN,Nawazuddin Siddiqui|Sanya Malhotra|Sachin Khed...,NaN,17 May 2019 (USA)
20,Mere Pyare Prime Minister,tt8207768,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mere_Pyare_Prime...,Mere Pyare Prime Minister,Mere Pyare Prime Minister,0,2018,104,Drama,6.8,344,A story about four children living in a Mumbai...,A story about four children living in a Mumbai...,Meri Ek Arzi Sun Lo Zara,Rasika Agashe|Sonia Albizuri|Syna Anand|Adarsh...,NaN,15 March 2019 (India)

In [43]:
movies.iloc[5:36:10]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
15,Badla (2019 film),tt8130968,https://upload.wikimedia.org/wikipedia/en/0/0c...,https://en.wikipedia.org/wiki/Badla_(2019_film),Badla,Badla,0,2019,118,Crime|Drama|Mystery,7.9,15499,Naina Sethi a successful entrepreneur finds he...,A dynamic young entrepreneur finds herself loc...,NaN,Amitabh Bachchan|Taapsee Pannu|Amrita Singh|An...,1 win,8 March 2019 (India)
25,Gone Kesh,tt10017956,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gone_Kesh,Gone Kesh,Gone Kesh,0,2019,110,Drama,7.1,178,Enakshi is diagnosed with Alopecia where she ...,Enakshi is diagnosed with Alopecia where she ...,NaN,Deepika Amin|Kumar Kanchan Ghosh|Brijendra Kal...,9 wins,29 March 2019 (India)
35,Khamoshi (2019 film),tt8268972,https://upload.wikimedia.org/wikipedia/en/e/ef...,https://en.wikipedia.org/wiki/Khamoshi_(2019_f...,Khamoshi,Khamoshi,0,2019,96,Horror|Thriller,3.7,153,A remake of an English movie Hush (2016) wher...,A remake of an English movie Hush (2016) wher...,NaN,Prabhu Deva|Tamannaah Bhatia|Bhoomika Chawla|,NaN,14 June 2019 (India)

In [44]:
movies.iloc[-15:]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1614,Moksha (2001 film),tt0301240,https://upload.wikimedia.org/wikipedia/en/6/6e...,https://en.wikipedia.org/wiki/Moksha_(2001_film),Moksha: Salvation,Moksha: Salvation,0,2001,150,Drama|Thriller,6.3,356,Appalled at the manner lawyers treat less affl...,An idealistic lawyer wants to help the poor ge...,NaN,Arjun Rampal|Manisha Koirala|Kalpana Pandit|Su...,3 wins & 2 nominations,30 November 2001 (India)
1615,Style (2001 film),tt0306855,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Style_(2001_film),Style,Style,0,2001,157,Comedy|Musical|Mystery,6.7,1607,Bantu and Chantu are two close friends and fel...,In an attempt to woo the rich women two prank...,NaN,Sharman Joshi|Sahil Khan|Riya Sen|Shilpi Sharm...,NaN,28 December 2001 (India)
1616,Rehnaa Hai Terre Dil Mein,tt0299108,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rehnaa_Hai_Terre...,Rehnaa Hai Terre Dil Mein,Rehnaa Hai Terre Dil Mein,0,2001,160,Musical|Romance,7.5,6232,Madhav (Maddy) has love at first site with Ree...,A young girl is torn between an obsessive love...,NaN,Madhavan|Saif Ali Khan|Dia Mirza|Vrajesh Hirje...,2 wins & 4 nominations,19 October 2001 (India)
1617,Officer (2001 film),tt0265452,NaN,https://en.wikipedia.org/wiki/Officer_(2001_film),Officer,Officer,0,2001,\N,Action|Crime|Drama,5.3,97,SPU unit officer Sagar Chauhan is assigned wit...,SPU unit officer Sagar Chauhan is assigned wit...,NaN,Sunil Shetty|Raveena Tandon|Danny Denzongpa|,NaN,14 March 2001 (Kuwait)
1618,Rahul (film),tt0277981,https://upload.wikimedia.org/wikipedia/en/f/f8...,https://en.wikipedia.org/wiki/Rahul_(film),Rahul,Rahul,0,2001,151,Drama,5.5,219,Mira (Neha) comes from a very wealthy family ...,Mira and Akash gets married despite against fa...,NaN,Neha|Rajeshwari Sachdev|Gulshan Grover|Nina Ku...,NaN,23 March 2001 (India)
1619,Pyaar Zindagi Hai,tt0847758,https://upload.wikimedia.org/wikipedia/en/5/5e...,https://en.wikipedia.org/wiki/Pyaar_Zindagi_Hai,Pyaar Zindagi Hai,Pyaar Zindagi Hai,0,2001,157,Drama|Romance|Thriller,6.6,39,After the marriage of his daughter Geeta wit...,After the marriage of his daughter Geeta wit...,NaN,Rajesh Khanna|Vikas Kalantri|Ashima Bhalla|Asa...,NaN,7 September 2001 (India)
1620,Yeh Raaste Hain Pyaar Ke,tt0292740,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Raaste_Hain_...,Yeh Raaste Hain Pyaar Ke,Yeh Raaste Hain Pyaar Ke,0,2001,149,Drama|Romance,4.0,607,Two con artistes and car thieves Vicky (Ajay ...,Two con artistes and car thieves Vicky (Ajay ...,Love is a journey... not a destination,Ajay Devgn|Madhuri Dixit|Preity Zinta|Vikram G...,NaN,10 August 2001 (India)
1621,Tum Bin,tt0290326,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Tum_Bin,Tum Bin...: Love Will Find a Way,Tum Bin...: Love Will Find a Way,0,2001,158,Drama|Romance,7.5,2879,Shekar and Amar meet at a party where Amar ask...,Shekhar accidentally kills his associate Amar ...,Love will find a way,Priyanshu Chatterjee|Himanshu Malik|Sandali Si...,6 nominations,13 July 2001 (India)
1622,Yeh Teraa Ghar Yeh Meraa Ghar,tt0298606,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Teraa_Ghar_Y...,Yeh Teraa Ghar Yeh Meraa Ghar,Yeh Teraa Ghar Yeh Meraa Ghar,0,2001,175,Comedy|Drama,5.7,704,In debt; Dayashankar Pandey is forced to go to...,In debt; Dayashankar Pandey is forced to go to...,NaN,Sunil Shetty|Mahima Chaudhry|Paresh Rawal|Saur...,1 nomination,12 October 2001 (India)
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [45]:
student = {
    "ID" : [101,102,103],
    "Marks" : [80,90,75],
    "Package" : [6,9,5]
}

students = pd.DataFrame(student)
students

    ID  Marks  Package
0  101     80        6
1  102     90        9
2  103     75        5

In [46]:
students.rename(columns={
    "ID": "Student_ID",
    "Marks": "Percentage",
    "Package": "LPA"
}, inplace=True)
students

   Student_ID  Percentage  LPA
0         101          80    6
1         102          90    9
2         103          75    5

# Concepts Covered

After completing these questions, you should be comfortable with

- ✅ Creating DataFrames
- ✅ Loading CSV files
- ✅ Exploring DataFrames
- ✅ DataFrame Attributes
- ✅ DataFrame Methods
- ✅ Mathematical Operations
- ✅ Missing Value Analysis
- ✅ Duplicate Detection
- ✅ Single Column Selection
- ✅ Multiple Column Selection
- ✅ Row Selection using `iloc`
- ✅ Renaming Columns
- ✅ Working with Real-World DataFrames