# Python Practice Questions - Session 5 (Pandas GroupBy)

## Topics Covered

- groupby()
- sum()
- mean()
- min()
- max()
- count()
- size()
- first()
- last()
- get_group()
- agg()

---

# Dataset

Use the following datasets:

- `imdb-top-1000.csv`
- `deliveries.csv`

You may also create your own DataFrames wherever required.

---

# Instructions

- Solve all questions in Jupyter Notebook.
- Use meaningful variable names.
- Add comments wherever necessary.
- Use only **Pandas** and **NumPy**.
- Test your program with multiple examples.
- Do not modify the original dataset unless explicitly instructed.

# Question 1 — Basic GroupBy Operations

## Dataset

`imdb-top-1000.csv`

## Problem Statement

Load the dataset into a DataFrame named `movies`.

### Requirements

1. Group the dataset by `Genre`.
2. Find the total number of movies in each genre.
3. Find the average IMDb rating of each genre.
4. Find the minimum IMDb rating of each genre.
5. Find the maximum IMDb rating of each genre.
6. Sort genres by average IMDb rating in descending order.
7. Display the top 10 genres.

### Example Output

```text
Genre

Western      8.30
Crime        8.01
Drama        7.98
...
```

In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv("imdb-top-1000.csv")
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [3]:
genre = movies.groupby("Genre")
genre

In [4]:
genre['Series_Title'].count()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
Name: Series_Title, dtype: int64

In [5]:
genre['IMDB_Rating'].mean()

Genre
Action       7.949419
Adventure    7.937500
Animation    7.930488
Biography    7.938636
Comedy       7.901290
Crime        8.016822
Drama        7.957439
Family       7.800000
Fantasy      8.000000
Film-Noir    7.966667
Horror       7.909091
Mystery      7.975000
Thriller     7.800000
Western      8.350000
Name: IMDB_Rating, dtype: float64

In [6]:
genre['IMDB_Rating'].min()

Genre
Action       7.6
Adventure    7.6
Animation    7.6
Biography    7.6
Comedy       7.6
Crime        7.6
Drama        7.6
Family       7.8
Fantasy      7.9
Film-Noir    7.8
Horror       7.6
Mystery      7.6
Thriller     7.8
Western      7.8
Name: IMDB_Rating, dtype: float64

In [7]:
genre['IMDB_Rating'].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

In [8]:
genre['IMDB_Rating'].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [9]:
genre['IMDB_Rating'].mean().sort_values(ascending=False).head(10)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Name: IMDB_Rating, dtype: float64

# Question 2 — GroupBy with Aggregation

## Dataset

`imdb-top-1000.csv`

## Problem Statement

Load the dataset into a DataFrame named `movies`.

### Requirements

Create a summary table for every genre containing:

1. Total Movies
2. Average Runtime
3. Average IMDb Rating
4. Total Gross Collection
5. Maximum Gross Collection
6. Minimum Gross Collection

Use only the `agg()` function.

### Example Output

```text
Genre

Action

Movies            172
Avg Runtime       128.3
Avg Rating        7.94
Total Gross       8.52e9
Max Gross         936630225
Min Gross         1305
```

In [10]:
movies = pd.read_csv("imdb-top-1000.csv")
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [11]:
genre = movies.groupby("Genre")
genre

In [12]:
genre['Series_Title'].count()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
Name: Series_Title, dtype: int64

In [13]:
genre['Runtime'].mean()

Genre
Action       129.046512
Adventure    134.111111
Animation     99.585366
Biography    136.022727
Comedy       112.129032
Crime        126.392523
Drama        124.737024
Family       107.500000
Fantasy       85.000000
Film-Noir    104.000000
Horror       102.090909
Mystery      119.083333
Thriller     108.000000
Western      148.250000
Name: Runtime, dtype: float64

In [14]:
genre['IMDB_Rating'].mean()

Genre
Action       7.949419
Adventure    7.937500
Animation    7.930488
Biography    7.938636
Comedy       7.901290
Crime        8.016822
Drama        7.957439
Family       7.800000
Fantasy      8.000000
Film-Noir    7.966667
Horror       7.909091
Mystery      7.975000
Thriller     7.800000
Western      8.350000
Name: IMDB_Rating, dtype: float64

In [15]:
genre["Gross"].sum()

Genre
Action       3.263226e+10
Adventure    9.496922e+09
Animation    1.463147e+10
Biography    8.276358e+09
Comedy       1.566387e+10
Crime        8.452632e+09
Drama        3.540997e+10
Family       4.391106e+08
Fantasy      7.827267e+08
Film-Noir    1.259105e+08
Horror       1.034649e+09
Mystery      1.256417e+09
Thriller     1.755074e+07
Western      5.822151e+07
Name: Gross, dtype: float64

In [16]:
genre["Gross"].max().sort_values(ascending=False)

Genre
Action       936662225.0
Drama        924558264.0
Comedy       886752933.0
Adventure    874211619.0
Animation    873839108.0
Crime        790482117.0
Biography    753585104.0
Mystery      474203697.0
Fantasy      445151978.0
Family       435110554.0
Horror       298791505.0
Film-Noir    123353292.0
Western       31800000.0
Thriller      17550741.0
Name: Gross, dtype: float64

In [17]:
genre["Gross"].min().sort_values(ascending=False)

Genre
Fantasy      337574718.0
Thriller      17550741.0
Western        5321508.0
Family         4000000.0
Mystery        1035953.0
Film-Noir       449191.0
Animation       128985.0
Horror           89029.0
Adventure        61001.0
Biography        21877.0
Crime             6013.0
Drama             3600.0
Action            3296.0
Comedy            1305.0
Name: Gross, dtype: float64

# Question 3 — IPL GroupBy Analysis

## Dataset

`deliveries.csv`

## Problem Statement

Load the dataset into a DataFrame named `ipl`.

### Requirements

1. Find total runs scored by every batsman.
2. Find total runs conceded by every bowler.
3. Find the number of balls bowled by every bowler.
4. Find the total number of fours hit by every batsman.
5. Find the total number of sixes hit by every batsman.
6. Display the top 10 run scorers.
7. Display the top 10 wicket-taking bowlers (ignore missing dismissals).

### Example Output

```text
Top Run Scorers

Virat Kohli      7263
Rohit Sharma     6211
Shikhar Dhawan   6170
...
```

In [18]:
ipl = pd.read_csv("deliveries.csv")
ipl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [19]:
batsman = ipl.groupby('batsman')
batsman

In [20]:
batsman['batsman_runs'].count().sort_values(ascending=False)

batsman
V Kohli           4211
SK Raina          4044
RG Sharma         3816
S Dhawan          3776
G Gambhir         3524
                  ...
S Lamichhane         1
C Nanda              1
Sunny Gupta          1
U Kaul               1
V Pratap Singh       1
Name: batsman_runs, Length: 516, dtype: int64

In [21]:
bowler = ipl.groupby('bowler')
bowler

In [22]:
bowler['batsman_runs'].count().sort_values(ascending=False)

bowler
Harbhajan Singh     3451
A Mishra            3172
PP Chawla           3157
R Ashwin            3016
SL Malinga          2974
                    ...
C Ganapathy            6
Y Gnaneswara Rao       6
SPD Smith              2
SN Khan                2
AC Gilchrist           1
Name: batsman_runs, Length: 405, dtype: int64

In [23]:
bowler['ball'].count().sort_values(ascending=False)

bowler
Harbhajan Singh     3451
A Mishra            3172
PP Chawla           3157
R Ashwin            3016
SL Malinga          2974
                    ...
C Ganapathy            6
Y Gnaneswara Rao       6
SPD Smith              2
SN Khan                2
AC Gilchrist           1
Name: ball, Length: 405, dtype: int64

In [24]:
fours = ipl[ipl['batsman_runs'] == 4].groupby('batsman').size()
fours

batsman
A Ashish Reddy     16
A Chopra            7
A Choudhary         1
A Flintoff          5
A Hales            13
                 ...
YK Pathan         264
YV Takawale        26
Yashpal Singh       5
Yuvraj Singh      218
Z Khan             11
Length: 410, dtype: int64

In [25]:
six = ipl[ipl['batsman_runs'] == 6].groupby('batsman').size()
six

batsman
A Ashish Reddy      15
A Choudhary          1
A Flintoff           2
A Hales              6
A Mishra             5
                  ...
Y Venugopal Rao     37
YK Pathan          161
YV Takawale          3
Yuvraj Singh       149
Z Khan               2
Length: 336, dtype: int64

In [26]:
batsman['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

In [27]:
wickets_df = ipl.dropna(subset=['player_dismissed'])
top_10_bowlers = wickets_df.groupby('bowler').size().sort_values(ascending=False).head(10)
top_10_bowlers

bowler
SL Malinga         188
DJ Bravo           168
A Mishra           165
Harbhajan Singh    161
PP Chawla          156
B Kumar            141
R Ashwin           138
SP Narine          137
UT Yadav           136
R Vinay Kumar      127
dtype: int64

# Question 4 — Exploring Groups

## Dataset

`imdb-top-1000.csv`

## Problem Statement

Load the dataset into a DataFrame named `movies`.

### Requirements

1. Find the total number of groups.
2. Find the number of movies in each genre.
3. Display the first movie from every genre.
4. Display the last movie from every genre.
5. Display the third movie from every genre (if available).
6. Display all Horror movies using `get_group()`.
7. Display all Animation movies using `get_group()`.

### Example Output

```text
Movies in Each Genre

Action        172
Drama         289
Comedy        155
...
```

In [28]:
movies = pd.read_csv("imdb-top-1000.csv")
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [29]:
genre = movies.groupby('Genre')
genre

In [30]:
len(genre)

14

In [31]:
genre['Series_Title'].count()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
Name: Series_Title, dtype: int64

In [32]:
genre.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [33]:
genre.last()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

In [34]:
genre.nth(2)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
8,Inception,2010,148,Action,8.8,Christopher Nolan,Leonardo DiCaprio,2067042,292576195.0,74.0
11,Forrest Gump,1994,142,Drama,8.8,Robert Zemeckis,Tom Hanks,1809221,330252182.0,82.0
18,Hamilton,2020,160,Biography,8.6,Thomas Kail,Lin-Manuel Miranda,55291,440984783.0,90.0
46,Hotaru no haka,1988,89,Animation,8.5,Isao Takahata,Tsutomu Tatsumi,235231,150734678.0,94.0
51,Modern Times,1936,87,Comedy,8.5,Charles Chaplin,Charles Chaplin,217881,163245.0,96.0
93,Inglourious Basterds,2009,153,Adventure,8.3,Quentin Tarantino,Brad Pitt,1267869,120540719.0,69.0
115,Per qualche dollaro in più,1965,132,Western,8.3,Sergio Leone,Clint Eastwood,232772,15000000.0,74.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
712,Shadow of a Doubt,1943,108,Film-Noir,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0

In [35]:
genre.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [36]:
genre.get_group('Animation')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
23,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
43,The Lion King,1994,88,Animation,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
46,Hotaru no haka,1988,89,Animation,8.5,Isao Takahata,Tsutomu Tatsumi,235231,150734678.0,94.0
56,Kimi no na wa.,2016,106,Animation,8.4,Makoto Shinkai,Ryûnosuke Kamiki,194838,5017246.0,79.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
...,...,...,...,...,...,...,...,...,...,...
956,Mulan,1998,88,Animation,7.6,Tony Bancroft,Barry Cook,256906,120620254.0,71.0
971,Omohide poro poro,1991,118,Animation,7.6,Isao Takahata,Miki Imai,27071,453243.0,90.0
976,The Little Mermaid,1989,83,Animation,7.6,Ron Clements,John Musker,237696,111543479.0,88.0
986,Watership Down,1978,91,Animation,7.6,Martin Rosen,John Hubley,33656,232841485.0,64.0
992,The Jungle Book,1967,78,Animation,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0

# Question 5 — Real-World GroupBy Problems

## Dataset

`imdb-top-1000.csv`

## Problem Statement

Load the dataset into a DataFrame named `movies`.

### Requirements

1. Find the top 5 genres by total gross earnings.
2. Find the genre having the highest average IMDb rating.
3. Find the director whose movies received the highest total number of votes.
4. Find the number of movies directed by each director.
5. Find the average runtime of movies directed by each director.
6. Find the top 10 directors based on average IMDb rating (minimum 5 movies).
7. Display the top 10 directors based on total gross earnings.

### Example Output

```text
Top Grossing Genres

Action       8.52e9
Adventure    6.97e9
Drama        5.84e9
...
```

In [37]:
movies = pd.read_csv("imdb-top-1000.csv")
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [38]:
genre = movies.groupby('Genre')
genre

In [39]:
genre['Gross'].sum().sort_values(ascending=False).head(5)

Genre
Drama        3.540997e+10
Action       3.263226e+10
Comedy       1.566387e+10
Animation    1.463147e+10
Adventure    9.496922e+09
Name: Gross, dtype: float64

In [40]:
genre['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [41]:
director = movies.groupby('Director')
director

In [42]:
director['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [43]:
movies_per_director = movies.groupby('Director')['Series_Title'].count().sort_values(ascending=False)
movies_per_director

Director
Alfred Hitchcock    14
Steven Spielberg    13
Hayao Miyazaki      11
Martin Scorsese     10
Akira Kurosawa      10
                    ..
Alan J. Pakula       1
Alain Resnais        1
Aditya Dhar          1
Bob Persichetti      1
Steve McQueen        1
Name: Series_Title, Length: 548, dtype: int64

In [44]:
director['Runtime'].mean().sort_values(ascending=False)

Director
Kenneth Branagh       242.0
Anurag Kashyap        232.5
Cecil B. DeMille      220.0
Ashutosh Gowariker    217.0
Ramesh Sippy          204.0
                      ...
René Laloux            72.0
Leo McCarey            69.0
Clyde Bruckman         67.0
Tod Browning           64.0
Buster Keaton          45.0
Name: Runtime, Length: 548, dtype: float64

In [45]:
director_stats = movies.groupby('Director').agg(
    movie_count=('Series_Title', 'count'),
    avg_rating=('IMDB_Rating', 'mean')
)
top_10_directors_by_rating = director_stats[director_stats['movie_count'] >= 5].sort_values(by='avg_rating', ascending=False).head(10)
top_10_directors_by_rating

                      movie_count  avg_rating
Director
Christopher Nolan               8    8.462500
Francis Ford Coppola            5    8.400000
Peter Jackson                   5    8.400000
Charles Chaplin                 6    8.333333
Sergio Leone                    6    8.266667
Stanley Kubrick                 9    8.233333
Akira Kurosawa                 10    8.220000
Quentin Tarantino               8    8.175000
Martin Scorsese                10    8.170000
Billy Wilder                    9    8.144444

In [46]:
director['Gross'].sum().sort_values(ascending=False).head(10)

Director
Akira Kurosawa       3.070432e+09
Steven Spielberg     2.478133e+09
Hayao Miyazaki       2.447325e+09
Alfred Hitchcock     2.337746e+09
Anthony Russo        2.205039e+09
Christopher Nolan    1.937454e+09
James Cameron        1.748237e+09
Ingmar Bergman       1.654929e+09
Peter Jackson        1.597312e+09
Billy Wilder         1.557238e+09
Name: Gross, dtype: float64

# Concepts Covered

After completing these questions, you should be comfortable with

- ✅ Creating GroupBy objects
- ✅ Applying aggregation functions
- ✅ Using `sum()`, `mean()`, `count()`, `size()`
- ✅ Finding minimum and maximum values
- ✅ Using `first()`, `last()`, and `nth()`
- ✅ Using `get_group()`
- ✅ Using `agg()` with multiple aggregations
- ✅ Solving real-world GroupBy problems
- ✅ Performing grouped exploratory data analysis (EDA)
- ✅ Working confidently with grouped datasets in Pandas