# Python Practice Questions - Session 19 (Pandas Merge, Join & Concat)

## Topics Covered

- pd.concat()
- merge()
- Inner Join
- Left Join
- Right Join
- Outer Join
- on
- left_on
- right_on
- suffixes
- MultiIndex (using keys)
- axis parameter

---

# Dataset

Use the following datasets:

- `students.csv`
- `courses.csv`
- `reg-month1.csv`
- `reg-month2.csv`
- `matches.csv`
- `deliveries.csv`

You may also create your own DataFrames wherever required.

---

# Instructions

- Solve all questions in Jupyter Notebook.
- Use meaningful variable names.
- Add comments wherever necessary.
- Use only **Pandas** and **NumPy**.
- Test your program with multiple examples.
- Do not modify the original dataset unless explicitly instructed.

# Question 1 — Concatenating DataFrames

## Dataset

`reg-month1.csv`
`reg-month2.csv`

## Problem Statement

Load both datasets into DataFrames named `nov` and `dec`.

### Requirements

1. Concatenate both DataFrames vertically.
2. Display the shape of the new DataFrame.
3. Concatenate them using `ignore_index=True`.
4. Create a MultiIndex DataFrame using `keys=['November','December']`.
5. Extract only the December registrations using `.loc[]`.
6. Concatenate both DataFrames horizontally.
7. Display the shape of the horizontally concatenated DataFrame.

### Example Output

```text
Shape

(53, 2)

December Registrations

student_id   course_id
...
```

In [1]:
import numpy as np
import pandas as pd

In [2]:
November = pd.read_csv("reg-month1.csv")
November

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [3]:
December = pd.read_csv("reg-month2.csv")
December

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [4]:
regs = pd.concat([November,December])
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [5]:
regs.shape

(53, 2)

In [6]:
regs = pd.concat([November,December],ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [7]:
regs = pd.concat([November,December],keys=['November','December'])
regs

             student_id  course_id
November 0           23          1
         1           15          5
         2           18          6
         3           23          4
         4           16          9
         5           18          1
         6            1          1
         7            7          8
         8           22          3
         9           15          1
         10          19          4
         11           1          6
         12           7         10
         13          11          7
         14          13          3
         15          24          4
         16          21          1
         17          16          5
         18          23          3
         19          17          7
         20          23          6
         21          25          1
         22          19          2
         23          25         10
         24           3          3
December 0            3          5
         1           16          7
         2           12         10
         3           12          1
         4           14          9
         5            7          7
         6            7          2
         7           16          3
         8           17         10
         9           11          8
         10          14          6
         11          12          5
         12          12          7
         13          18          8
         14           1         10
         15           1          9
         16           2          5
         17           7          6
         18          22          5
         19          22          6
         20          23          9
         21          23          5
         22          14          4
         23          14          1
         24          11         10
         25          42          9
         26          50          8
         27          38          1

In [8]:
regs.loc['December']

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [9]:
regs = pd.concat([November,December],axis = 1)
regs

    student_id  course_id  student_id  course_id
0         23.0        1.0           3          5
1         15.0        5.0          16          7
2         18.0        6.0          12         10
3         23.0        4.0          12          1
4         16.0        9.0          14          9
5         18.0        1.0           7          7
6          1.0        1.0           7          2
7          7.0        8.0          16          3
8         22.0        3.0          17         10
9         15.0        1.0          11          8
10        19.0        4.0          14          6
11         1.0        6.0          12          5
12         7.0       10.0          12          7
13        11.0        7.0          18          8
14        13.0        3.0           1         10
15        24.0        4.0           1          9
16        21.0        1.0           2          5
17        16.0        5.0           7          6
18        23.0        3.0          22          5
19        17.0        7.0          22          6
20        23.0        6.0          23          9
21        25.0        1.0          23          5
22        19.0        2.0          14          4
23        25.0       10.0          14          1
24         3.0        3.0          11         10
25         NaN        NaN          42          9
26         NaN        NaN          50          8
27         NaN        NaN          38          1

In [10]:
regs.shape

(28, 4)

# Question 2 — Finding Total Revenue

## Dataset

`courses.csv`
`reg-month1.csv`
`reg-month2.csv`

## Problem Statement

Load all datasets.

### Requirements

1. Combine November and December registrations.
2. Merge the registration DataFrame with the courses DataFrame.
3. Calculate the total revenue generated.
4. Calculate the average course price purchased.
5. Find the most expensive purchased course.
6. Find the cheapest purchased course.

### Example Output

```text
Total Revenue

314100
```

In [11]:
nov = pd.read_csv('reg-month1.csv')
dec = pd.read_csv('reg-month2.csv')
courses = pd.read_csv('courses.csv')
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [12]:
regs = pd.concat([nov,dec],ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [13]:
regs.merge(courses,on='course_id')

    student_id  course_id       course_name  price
0           23          1            python   2499
1           15          5           tableau   2499
2           18          6          power bi   1899
3           23          4  machine learning   9999
4           16          9            plotly    699
5           18          1            python   2499
6            1          1            python   2499
7            7          8            pandas   1099
8           22          3     data analysis   4999
9           15          1            python   2499
10          19          4  machine learning   9999
11           1          6          power bi   1899
12           7         10           pyspark   2499
13          11          7          ms sxcel   1599
14          13          3     data analysis   4999
15          24          4  machine learning   9999
16          21          1            python   2499
17          16          5           tableau   2499
18          23          3     data analysis   4999
19          17          7          ms sxcel   1599
20          23          6          power bi   1899
21          25          1            python   2499
22          19          2               sql   3499
23          25         10           pyspark   2499
24           3          3     data analysis   4999
25           3          5           tableau   2499
26          16          7          ms sxcel   1599
27          12         10           pyspark   2499
28          12          1            python   2499
29          14          9            plotly    699
30           7          7          ms sxcel   1599
31           7          2               sql   3499
32          16          3     data analysis   4999
33          17         10           pyspark   2499
34          11          8            pandas   1099
35          14          6          power bi   1899
36          12          5           tableau   2499
37          12          7          ms sxcel   1599
38          18          8            pandas   1099
39           1         10           pyspark   2499
40           1          9            plotly    699
41           2          5           tableau   2499
42           7          6          power bi   1899
43          22          5           tableau   2499
44          22          6          power bi   1899
45          23          9            plotly    699
46          23          5           tableau   2499
47          14          4  machine learning   9999
48          14          1            python   2499
49          11         10           pyspark   2499
50          42          9            plotly    699
51          50          8            pandas   1099
52          38          1            python   2499

In [14]:
print(regs.merge(courses,on='course_id')['price'].mean())

2910.3207547169814

In [15]:
regs.merge(courses,on='course_id').loc[regs.merge(courses,on='course_id')['price'].idxmax()]

student_id                   23
course_id                     4
course_name    machine learning
price                      9999
Name: 3, dtype: object

In [16]:
regs.merge(courses,on='course_id').loc[regs.merge(courses,on='course_id')['price'].idxmin()]

student_id         16
course_id           9
course_name    plotly
price             699
Name: 4, dtype: object

# Question 3 — Month-wise Revenue Analysis

## Dataset

`courses.csv`
`reg-month1.csv`
`reg-month2.csv`

## Problem Statement

Load all datasets.

### Requirements

1. Create a MultiIndex registration DataFrame using `keys`.
2. Convert the MultiIndex into columns using `reset_index()`.
3. Merge it with the courses DataFrame.
4. Find revenue generated in each month.
5. Find the average course price purchased in each month.
6. Find the total number of enrollments in each month.

### Example Output

```text
Revenue

November    248000
December    66100
```

In [17]:
nov = pd.read_csv('reg-month1.csv')
dec = pd.read_csv('reg-month2.csv')
courses = pd.read_csv('courses.csv')
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [18]:
regs = pd.concat([nov,dec],keys=['Nov','Dec'])
regs

        student_id  course_id
Nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
Dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [19]:
regs_df = regs.reset_index().rename(columns={'level_0': 'Month'})
regs_df

   Month  level_1  student_id  course_id
0    Nov        0          23          1
1    Nov        1          15          5
2    Nov        2          18          6
3    Nov        3          23          4
4    Nov        4          16          9
5    Nov        5          18          1
6    Nov        6           1          1
7    Nov        7           7          8
8    Nov        8          22          3
9    Nov        9          15          1
10   Nov       10          19          4
11   Nov       11           1          6
12   Nov       12           7         10
13   Nov       13          11          7
14   Nov       14          13          3
15   Nov       15          24          4
16   Nov       16          21          1
17   Nov       17          16          5
18   Nov       18          23          3
19   Nov       19          17          7
20   Nov       20          23          6
21   Nov       21          25          1
22   Nov       22          19          2
23   Nov       23          25         10
24   Nov       24           3          3
25   Dec        0           3          5
26   Dec        1          16          7
27   Dec        2          12         10
28   Dec        3          12          1
29   Dec        4          14          9
30   Dec        5           7          7
31   Dec        6           7          2
32   Dec        7          16          3
33   Dec        8          17         10
34   Dec        9          11          8
35   Dec       10          14          6
36   Dec       11          12          5
37   Dec       12          12          7
38   Dec       13          18          8
39   Dec       14           1         10
40   Dec       15           1          9
41   Dec       16           2          5
42   Dec       17           7          6
43   Dec       18          22          5
44   Dec       19          22          6
45   Dec       20          23          9
46   Dec       21          23          5
47   Dec       22          14          4
48   Dec       23          14          1
49   Dec       24          11         10
50   Dec       25          42          9
51   Dec       26          50          8
52   Dec       27          38          1

In [20]:
merge_df = regs_df.merge(courses,on='course_id',how='inner')
merge_df

   Month  level_1  student_id  course_id       course_name  price
0    Nov        0          23          1            python   2499
1    Nov        1          15          5           tableau   2499
2    Nov        2          18          6          power bi   1899
3    Nov        3          23          4  machine learning   9999
4    Nov        4          16          9            plotly    699
5    Nov        5          18          1            python   2499
6    Nov        6           1          1            python   2499
7    Nov        7           7          8            pandas   1099
8    Nov        8          22          3     data analysis   4999
9    Nov        9          15          1            python   2499
10   Nov       10          19          4  machine learning   9999
11   Nov       11           1          6          power bi   1899
12   Nov       12           7         10           pyspark   2499
13   Nov       13          11          7          ms sxcel   1599
14   Nov       14          13          3     data analysis   4999
15   Nov       15          24          4  machine learning   9999
16   Nov       16          21          1            python   2499
17   Nov       17          16          5           tableau   2499
18   Nov       18          23          3     data analysis   4999
19   Nov       19          17          7          ms sxcel   1599
20   Nov       20          23          6          power bi   1899
21   Nov       21          25          1            python   2499
22   Nov       22          19          2               sql   3499
23   Nov       23          25         10           pyspark   2499
24   Nov       24           3          3     data analysis   4999
25   Dec        0           3          5           tableau   2499
26   Dec        1          16          7          ms sxcel   1599
27   Dec        2          12         10           pyspark   2499
28   Dec        3          12          1            python   2499
29   Dec        4          14          9            plotly    699
30   Dec        5           7          7          ms sxcel   1599
31   Dec        6           7          2               sql   3499
32   Dec        7          16          3     data analysis   4999
33   Dec        8          17         10           pyspark   2499
34   Dec        9          11          8            pandas   1099
35   Dec       10          14          6          power bi   1899
36   Dec       11          12          5           tableau   2499
37   Dec       12          12          7          ms sxcel   1599
38   Dec       13          18          8            pandas   1099
39   Dec       14           1         10           pyspark   2499
40   Dec       15           1          9            plotly    699
41   Dec       16           2          5           tableau   2499
42   Dec       17           7          6          power bi   1899
43   Dec       18          22          5           tableau   2499
44   Dec       19          22          6          power bi   1899
45   Dec       20          23          9            plotly    699
46   Dec       21          23          5           tableau   2499
47   Dec       22          14          4  machine learning   9999
48   Dec       23          14          1            python   2499
49   Dec       24          11         10           pyspark   2499
50   Dec       25          42          9            plotly    699
51   Dec       26          50          8            pandas   1099
52   Dec       27          38          1            python   2499

In [21]:
merge_df.groupby('Month')['price'].sum()

Month
Dec    65072
Nov    89175
Name: price, dtype: int64

In [22]:
merge_df.groupby('Month')['price'].mean()

Month
Dec    2324.0
Nov    3567.0
Name: price, dtype: float64

In [23]:
merge_df.groupby('Month')['student_id'].count()

Month
Dec    28
Nov    25
Name: student_id, dtype: int64

# Question 4 — Student Registration Report

## Dataset

`students.csv`
`courses.csv`
`reg-month1.csv`
`reg-month2.csv`

## Problem Statement

Load all datasets.

### Requirements

Create a registration report containing:

1. Student Name
2. Course Name
3. Course Price
4. Registration Month

Use only merge operations.

### Example Output

```text
Name      Course          Price     Month

Rahul     Python          4999      November
Amit      SQL             2999      December
...
```

In [24]:
nov = pd.read_csv('reg-month1.csv')
nov

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [25]:
dec = pd.read_csv('reg-month2.csv')
dec

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [26]:
courses = pd.read_csv('courses.csv')
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [27]:
students = pd.read_csv('students.csv')
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [28]:
regs = pd.concat([nov,dec],keys=['Nov','Dec'])
regs

        student_id  course_id
Nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
Dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [29]:
regs_idx = regs.reset_index().rename(columns={'level_0':'Month'})
regs_idx

   Month  level_1  student_id  course_id
0    Nov        0          23          1
1    Nov        1          15          5
2    Nov        2          18          6
3    Nov        3          23          4
4    Nov        4          16          9
5    Nov        5          18          1
6    Nov        6           1          1
7    Nov        7           7          8
8    Nov        8          22          3
9    Nov        9          15          1
10   Nov       10          19          4
11   Nov       11           1          6
12   Nov       12           7         10
13   Nov       13          11          7
14   Nov       14          13          3
15   Nov       15          24          4
16   Nov       16          21          1
17   Nov       17          16          5
18   Nov       18          23          3
19   Nov       19          17          7
20   Nov       20          23          6
21   Nov       21          25          1
22   Nov       22          19          2
23   Nov       23          25         10
24   Nov       24           3          3
25   Dec        0           3          5
26   Dec        1          16          7
27   Dec        2          12         10
28   Dec        3          12          1
29   Dec        4          14          9
30   Dec        5           7          7
31   Dec        6           7          2
32   Dec        7          16          3
33   Dec        8          17         10
34   Dec        9          11          8
35   Dec       10          14          6
36   Dec       11          12          5
37   Dec       12          12          7
38   Dec       13          18          8
39   Dec       14           1         10
40   Dec       15           1          9
41   Dec       16           2          5
42   Dec       17           7          6
43   Dec       18          22          5
44   Dec       19          22          6
45   Dec       20          23          9
46   Dec       21          23          5
47   Dec       22          14          4
48   Dec       23          14          1
49   Dec       24          11         10
50   Dec       25          42          9
51   Dec       26          50          8
52   Dec       27          38          1

In [30]:
merge_df = students.merge(regs_idx,on='student_id').merge(courses,on='course_id')
merge_df[['name','course_name','price','Month']]

                  name       course_name  price Month
0        Kailash Harjo            python   2499   Nov
1        Kailash Harjo          power bi   1899   Nov
2        Kailash Harjo           pyspark   2499   Dec
3        Kailash Harjo            plotly    699   Dec
4          Esha Butala           tableau   2499   Dec
5       Parveen Bhalla     data analysis   4999   Nov
6       Parveen Bhalla           tableau   2499   Dec
7         Tarun Thaker            pandas   1099   Nov
8         Tarun Thaker           pyspark   2499   Nov
9         Tarun Thaker          ms sxcel   1599   Dec
10        Tarun Thaker               sql   3499   Dec
11        Tarun Thaker          power bi   1899   Dec
12  David Mukhopadhyay          ms sxcel   1599   Nov
13  David Mukhopadhyay            pandas   1099   Dec
14  David Mukhopadhyay           pyspark   2499   Dec
15          Radha Dutt           pyspark   2499   Dec
16          Radha Dutt            python   2499   Dec
17          Radha Dutt           tableau   2499   Dec
18          Radha Dutt          ms sxcel   1599   Dec
19      Munni Varghese     data analysis   4999   Nov
20    Pranab Natarajan            plotly    699   Dec
21    Pranab Natarajan          power bi   1899   Dec
22    Pranab Natarajan  machine learning   9999   Dec
23    Pranab Natarajan            python   2499   Dec
24           Preet Sha           tableau   2499   Nov
25           Preet Sha            python   2499   Nov
26        Elias Dodiya            plotly    699   Nov
27        Elias Dodiya           tableau   2499   Nov
28        Elias Dodiya          ms sxcel   1599   Dec
29        Elias Dodiya     data analysis   4999   Dec
30        Yasmin Palan          ms sxcel   1599   Nov
31        Yasmin Palan           pyspark   2499   Dec
32     Fardeen Mahabir          power bi   1899   Nov
33     Fardeen Mahabir            python   2499   Nov
34     Fardeen Mahabir            pandas   1099   Dec
35        Qabeel Raman  machine learning   9999   Nov
36        Qabeel Raman               sql   3499   Nov
37          Seema Kota            python   2499   Nov
38          Yash Sethi     data analysis   4999   Nov
39          Yash Sethi           tableau   2499   Dec
40          Yash Sethi          power bi   1899   Dec
41      Chhavi Lachman            python   2499   Nov
42      Chhavi Lachman  machine learning   9999   Nov
43      Chhavi Lachman     data analysis   4999   Nov
44      Chhavi Lachman          power bi   1899   Nov
45      Chhavi Lachman            plotly    699   Dec
46      Chhavi Lachman           tableau   2499   Dec
47        Radhika Suri  machine learning   9999   Nov
48     Shashank D’Alia            python   2499   Nov
49     Shashank D’Alia           pyspark   2499   Nov

# Question 5 — Join Types

## Dataset

`students.csv`
`reg-month2.csv`

## Problem Statement

Load both datasets.

### Requirements

Perform the following joins using `student_id`.

1. Inner Join
2. Left Join
3. Right Join
4. Outer Join

For every join:

- Display the shape.
- Count missing values.
- Explain which rows are included.

### Example Output

```text
Inner Join Shape

(50, 4)

Outer Join Shape

(56, 4)
```

In [31]:
dec = pd.read_csv('reg-month2.csv')
dec

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [32]:
students = pd.read_csv('students.csv')
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [33]:
inner_join = students.merge(dec,on='student_id',how='inner')
inner_join

    student_id                name  partner  course_id
0           14    Pranab Natarajan       22          6
1           14    Pranab Natarajan       22          4
2            3      Parveen Bhalla        3          5
3            7        Tarun Thaker        9          2
4            7        Tarun Thaker        9          6
5           17        Yasmin Palan        7         10
6           12          Radha Dutt       19          1
7           11  David Mukhopadhyay       20          8
8           11  David Mukhopadhyay       20         10
9           18     Fardeen Mahabir       13          8
10          12          Radha Dutt       19          7
11          16        Elias Dodiya       25          3
12           1       Kailash Harjo       23         10
13          12          Radha Dutt       19         10
14           1       Kailash Harjo       23          9
15          16        Elias Dodiya       25          7
16          12          Radha Dutt       19          5
17          14    Pranab Natarajan       22          9
18           2         Esha Butala        1          5
19          22          Yash Sethi       21          5
20          22          Yash Sethi       21          6
21          14    Pranab Natarajan       22          1
22           7        Tarun Thaker        9          7
23          23      Chhavi Lachman       18          9
24          23      Chhavi Lachman       18          5

In [34]:
inner_join.shape

(25, 4)

In [35]:
left_join = students.merge(dec,on='student_id',how='left')
left_join

    student_id                name  partner  course_id
0            1       Kailash Harjo       23       10.0
1            1       Kailash Harjo       23        9.0
2            2         Esha Butala        1        5.0
3            3      Parveen Bhalla        3        5.0
4            4         Marlo Dugal       14        NaN
5            5         Kusum Bahri        6        NaN
6            6  Lakshmi Contractor       10        NaN
7            7        Tarun Thaker        9        7.0
8            7        Tarun Thaker        9        2.0
9            7        Tarun Thaker        9        6.0
10           8      Radheshyam Dey        5        NaN
11           9   Nitika Chatterjee        4        NaN
12          10      Aayushman Sant        8        NaN
13          11  David Mukhopadhyay       20        8.0
14          11  David Mukhopadhyay       20       10.0
15          12          Radha Dutt       19       10.0
16          12          Radha Dutt       19        1.0
17          12          Radha Dutt       19        5.0
18          12          Radha Dutt       19        7.0
19          13      Munni Varghese       24        NaN
20          14    Pranab Natarajan       22        9.0
21          14    Pranab Natarajan       22        6.0
22          14    Pranab Natarajan       22        4.0
23          14    Pranab Natarajan       22        1.0
24          15           Preet Sha       16        NaN
25          16        Elias Dodiya       25        7.0
26          16        Elias Dodiya       25        3.0
27          17        Yasmin Palan        7       10.0
28          18     Fardeen Mahabir       13        8.0
29          19        Qabeel Raman       12        NaN
30          20       Hanuman Hegde       11        NaN
31          21          Seema Kota       15        NaN
32          22          Yash Sethi       21        5.0
33          22          Yash Sethi       21        6.0
34          23      Chhavi Lachman       18        9.0
35          23      Chhavi Lachman       18        5.0
36          24        Radhika Suri       17        NaN
37          25     Shashank D’Alia        2        NaN

In [36]:
left_join.shape

(38, 4)

In [37]:
right_join = students.merge(dec,on='student_id',how='right')
right_join

    student_id                name  partner  course_id
0            3      Parveen Bhalla      3.0          5
1           16        Elias Dodiya     25.0          7
2           12          Radha Dutt     19.0         10
3           12          Radha Dutt     19.0          1
4           14    Pranab Natarajan     22.0          9
5            7        Tarun Thaker      9.0          7
6            7        Tarun Thaker      9.0          2
7           16        Elias Dodiya     25.0          3
8           17        Yasmin Palan      7.0         10
9           11  David Mukhopadhyay     20.0          8
10          14    Pranab Natarajan     22.0          6
11          12          Radha Dutt     19.0          5
12          12          Radha Dutt     19.0          7
13          18     Fardeen Mahabir     13.0          8
14           1       Kailash Harjo     23.0         10
15           1       Kailash Harjo     23.0          9
16           2         Esha Butala      1.0          5
17           7        Tarun Thaker      9.0          6
18          22          Yash Sethi     21.0          5
19          22          Yash Sethi     21.0          6
20          23      Chhavi Lachman     18.0          9
21          23      Chhavi Lachman     18.0          5
22          14    Pranab Natarajan     22.0          4
23          14    Pranab Natarajan     22.0          1
24          11  David Mukhopadhyay     20.0         10
25          42                 NaN      NaN          9
26          50                 NaN      NaN          8
27          38                 NaN      NaN          1

In [38]:
right_join.shape

(28, 4)

In [39]:
outer_join = students.merge(dec,on='student_id',how='outer')
outer_join

    student_id                name  partner  course_id
0            1       Kailash Harjo     23.0       10.0
1            1       Kailash Harjo     23.0        9.0
2            2         Esha Butala      1.0        5.0
3            3      Parveen Bhalla      3.0        5.0
4            4         Marlo Dugal     14.0        NaN
5            5         Kusum Bahri      6.0        NaN
6            6  Lakshmi Contractor     10.0        NaN
7            7        Tarun Thaker      9.0        7.0
8            7        Tarun Thaker      9.0        2.0
9            7        Tarun Thaker      9.0        6.0
10           8      Radheshyam Dey      5.0        NaN
11           9   Nitika Chatterjee      4.0        NaN
12          10      Aayushman Sant      8.0        NaN
13          11  David Mukhopadhyay     20.0        8.0
14          11  David Mukhopadhyay     20.0       10.0
15          12          Radha Dutt     19.0       10.0
16          12          Radha Dutt     19.0        1.0
17          12          Radha Dutt     19.0        5.0
18          12          Radha Dutt     19.0        7.0
19          13      Munni Varghese     24.0        NaN
20          14    Pranab Natarajan     22.0        9.0
21          14    Pranab Natarajan     22.0        6.0
22          14    Pranab Natarajan     22.0        4.0
23          14    Pranab Natarajan     22.0        1.0
24          15           Preet Sha     16.0        NaN
25          16        Elias Dodiya     25.0        7.0
26          16        Elias Dodiya     25.0        3.0
27          17        Yasmin Palan      7.0       10.0
28          18     Fardeen Mahabir     13.0        8.0
29          19        Qabeel Raman     12.0        NaN
30          20       Hanuman Hegde     11.0        NaN
31          21          Seema Kota     15.0        NaN
32          22          Yash Sethi     21.0        5.0
33          22          Yash Sethi     21.0        6.0
34          23      Chhavi Lachman     18.0        9.0
35          23      Chhavi Lachman     18.0        5.0
36          24        Radhika Suri     17.0        NaN
37          25     Shashank D’Alia      2.0        NaN
38          38                 NaN      NaN        1.0
39          42                 NaN      NaN        9.0
40          50                 NaN      NaN        8.0

In [40]:
outer_join.shape

(41, 4)

# Question 6 — Merge on Different Column Names

## Problem Statement

Create two DataFrames.

### DataFrame 1

```text
emp_id   Name
1        Rahul
2        Aman
3        Neha
```

### DataFrame 2

```text
employee_id   Salary
1             45000
2             52000
4             38000
```

### Requirements

1. Merge both DataFrames.
2. Use `left_on` and `right_on`.
3. Perform Inner Join.
4. Perform Left Join.
5. Perform Outer Join.
6. Display missing values.

### Example Output

```text
emp_id   Name    Salary

1        Rahul   45000
2        Aman    52000
3        Neha      NaN
```

In [41]:
name = {
    'emp_id' : [1,2,3],
    'Name' : ['Rahul','Aman','Neha']
}
name = pd.DataFrame(name)
name

   emp_id   Name
0       1  Rahul
1       2   Aman
2       3   Neha

In [42]:
salary = {
    'employee_id' : [1,2,4],
    'Salary' : [45000,52000,38000]
}
salary = pd.DataFrame(salary)
salary

   employee_id  Salary
0            1   45000
1            2   52000
2            4   38000

In [43]:
merge_df = name.merge(salary,left_on='emp_id',right_on='employee_id')
merge_df

   emp_id   Name  employee_id  Salary
0       1  Rahul            1   45000
1       2   Aman            2   52000

In [44]:
inner_join = name.merge(salary,left_on='emp_id',right_on='employee_id',how='inner')
inner_join

   emp_id   Name  employee_id  Salary
0       1  Rahul            1   45000
1       2   Aman            2   52000

In [45]:
left_join = name.merge(salary,left_on='emp_id',right_on='employee_id',how='left')
left_join

   emp_id   Name  employee_id   Salary
0       1  Rahul          1.0  45000.0
1       2   Aman          2.0  52000.0
2       3   Neha          NaN      NaN

In [46]:
outer_join = name.merge(salary,left_on='emp_id',right_on='employee_id',how='outer')
outer_join

   emp_id   Name  employee_id   Salary
0     1.0  Rahul          1.0  45000.0
1     2.0   Aman          2.0  52000.0
2     3.0   Neha          NaN      NaN
3     NaN    NaN          4.0  38000.0

In [47]:
outer_join.isna().sum()

emp_id         1
Name           1
employee_id    1
Salary         1
dtype: int64

# Question 7 — IPL Merge Analysis

## Dataset

`matches.csv`
`deliveries.csv`

## Problem Statement

Load both datasets.

### Requirements

1. Merge both datasets using `match_id`.
2. Display the merged DataFrame shape.
3. Find total runs scored in every season.
4. Find the season with the highest total runs.
5. Find the number of matches played every season.
6. Find total wickets taken every season (ignore missing dismissals).

### Example Output

```text
Season

2008    17937
2009    16320
...
```

In [48]:
deliveries = pd.read_csv("deliveries.csv")
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [49]:
ipl = pd.read_csv("matches.csv")
ipl

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [50]:
merge_df = ipl.merge(deliveries,right_on='match_id',left_on='id')
merge_df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [51]:
merge_df.shape

(150460, 39)

In [52]:
merge_df.groupby('season')['batsman_runs'].sum()

season
2008    16809
2009    15376
2010    17754
2011    19928
2012    21322
2013    21487
2014    17943
2015    17427
2016    17963
2017    17920
Name: batsman_runs, dtype: int64

In [53]:
merge_df.groupby('season')['batsman_runs'].sum().sort_values(ascending=False).head(1)

season
2013    21487
Name: batsman_runs, dtype: int64

In [54]:
ipl.groupby('season')['id'].count()

season
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
2017    59
Name: id, dtype: int64

In [55]:
wickets_df = merge_df.dropna(subset=['dismissal_kind'])
wickets_df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
11,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
64,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,S Dhawan,caught,Sachin Baby
94,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,MC Henriques,caught,Sachin Baby
116,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,Yuvraj Singh,bowled,NaN
160,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,...,0,0,0,0,0,0,0,Mandeep Singh,bowled,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150422,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,0,0,0,AB de Villiers,caught,MC Henriques
150432,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,0,0,0,KL Rahul,bowled,NaN
150438,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,0,0,0,SR Watson,caught,MC Henriques
150448,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,1,0,1,STR Binny,run out,DJ Hooda
150456,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha

In [56]:
wickets_df.groupby('season')['dismissal_kind'].count()

season
2008    690
2009    698
2010    725
2011    813
2012    858
2013    912
2014    674
2015    691
2016    666
2017    711
Name: dismissal_kind, dtype: int64

# Question 8 — Real-World Merge Problems

## Dataset

`students.csv`
`courses.csv`
`reg-month1.csv`
`reg-month2.csv`

## Problem Statement

Load all datasets.

### Requirements

1. Find the student who spent the highest amount.
2. Find total revenue generated by each course.
3. Find the most popular course (highest enrollments).
4. Find students who enrolled in both months.
5. Find students who enrolled only in November.
6. Find students who enrolled only in December.
7. Find courses that were never purchased.
8. Find the average spending per student.

### Example Output

```text
Top Spending Student

Rahul     14997
```

In [57]:
students = pd.read_csv("students.csv")
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [58]:
courses = pd.read_csv('courses.csv')
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [59]:
nov = pd.read_csv('reg-month1.csv')
nov

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [60]:
dec = pd.read_csv('reg-month2.csv')
dec

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [61]:
regs = pd.concat([nov, dec], ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [62]:
full_df = regs.merge(students, on='student_id', how='inner').merge(courses, on='course_id', how='inner')
full_df

,student_id,course_id,name,partner,course_name,price
0,23,1,Chhavi Lachman,18,python,2499
1,15,5,Preet Sha,16,tableau,2499
2,18,6,Fardeen Mahabir,13,power bi,1899
3,23,4,Chhavi Lachman,18,machine learning,9999
4,16,9,Elias Dodiya,25,plotly,699
5,18,1,Fardeen Mahabir,13,python,2499
6,1,1,Kailash Harjo,23,python,2499
7,7,8,Tarun Thaker,9,pandas,1099
8,22,3,Yash Sethi,21,data analysis,4999
9,15,1,Preet Sha,16,python,2499
10,19,4,Qabeel Raman,12,machine learning,9999
11,1,6,Kailash Harjo,23,power bi,1899
12,7,10,Tarun Thaker,9,pyspark,2499
13,11,7,David Mukhopadhyay,20,ms sxcel,1599
14,13,3,Munni Varghese,24,data analysis,4999
15,24,4,Radhika Suri,17,machine learning,9999
16,21,1,Seema Kota,15,python,2499
17,16,5,Elias Dodiya,25,tableau,2499
18,23,3,Chhavi Lachman,18,data analysis,4999
19,17,7,Yasmin Palan,7,ms sxcel,1599
20,23,6,Chhavi Lachman,18,power bi,1899
21,25,1,Shashank D’Alia,2,python,2499
22,19,2,Qabeel Raman,12,sql,3499
23,25,10,Shashank D’Alia,2,pyspark,2499
24,3,3,Parveen Bhalla,3,data analysis,4999
25,3,5,Parveen Bhalla,3,tableau,2499
26,16,7,Elias Dodiya,25,ms sxcel,1599
27,12,10,Radha Dutt,19,pyspark,2499
28,12,1,Radha Dutt,19,python,2499
29,14,9,Pranab Natarajan,22,plotly,699
30,7,7,Tarun Thaker,9,ms sxcel,1599
31,7,2,Tarun Thaker,9,sql,3499
32,16,3,Elias Dodiya,25,data analysis,4999
33,17,10,Yasmin Palan,7,pyspark,2499
34,11,8,David Mukhopadhyay,20,pandas,1099
35,14,6,Pranab Natarajan,22,power bi,1899
36,12,5,Radha Dutt,19,tableau,2499
37,12,7,Radha Dutt,19,ms sxcel,1599
38,18,8,Fardeen Mahabir,13,pandas,1099
39,1,10,Kailash Harjo,23,pyspark,2499
40,1,9,Kailash Harjo,23,plotly,699
41,2,5,Esha Butala,1,tableau,2499
42,7,6,Tarun Thaker,9,power bi,1899
43,22,5,Yash Sethi,21,tableau,2499
44,22,6,Yash Sethi,21,power bi,1899
45,23,9,Chhavi Lachman,18,plotly,699
46,23,5,Chhavi Lachman,18,tableau,2499
47,14,4,Pranab Natarajan,22,machine learning,9999
48,14,1,Pranab Natarajan,22,python,2499
49,11,10,David Mukhopadhyay,20,pyspark,2499

In [63]:
full_df.groupby('name')['price'].sum().sort_values(ascending=False).head(1)

name
Chhavi Lachman    22594
Name: price, dtype: int64

In [64]:
full_df.groupby('course_name')['price'].sum()

course_name
data analysis       24995
machine learning    39996
ms sxcel             7995
pandas               3297
plotly               2796
power bi            11394
pyspark             14994
python              19992
sql                  6998
tableau             17493
Name: price, dtype: int64

In [65]:
full_df.groupby('course_name')['student_id'].sum().sort_values(ascending=False)

course_name
python              129
tableau              93
power bi             85
machine learning     80
data analysis        77
pyspark              73
ms sxcel             63
plotly               54
pandas               36
sql                  26
Name: student_id, dtype: int64

In [66]:
both_months_ids = set(nov['student_id']).intersection(set(dec['student_id']))
students_both_months = students[students['student_id'].isin(both_months_ids)]['name']
students_both_months

0          Kailash Harjo
2         Parveen Bhalla
6           Tarun Thaker
10    David Mukhopadhyay
15          Elias Dodiya
16          Yasmin Palan
17       Fardeen Mahabir
21            Yash Sethi
22        Chhavi Lachman
Name: name, dtype: str

In [67]:
nov_only_ids = set(nov['student_id']) - set(dec['student_id'])
students_nov_only = students[students['student_id'].isin(nov_only_ids)]['name']
students_nov_only

12     Munni Varghese
14          Preet Sha
18       Qabeel Raman
20         Seema Kota
23       Radhika Suri
24    Shashank D’Alia
Name: name, dtype: str

In [68]:
dec_only_ids = set(dec['student_id']) - set(nov['student_id'])
students_dec_only = students[students['student_id'].isin(dec_only_ids)]['name']
students_dec_only

1          Esha Butala
11          Radha Dutt
13    Pranab Natarajan
Name: name, dtype: str

In [69]:
purchased_course_ids = regs['course_id'].unique()
never_purchased_courses = courses[~courses['course_id'].isin(purchased_course_ids)]['course_name']
never_purchased_courses

10    Numpy
11      C++
Name: course_name, dtype: str

In [70]:
total_revenue = full_df['price'].sum()
unique_registered_students = full_df['student_id'].nunique()
avg_spending = total_revenue / unique_registered_students
avg_spending

np.float64(8330.555555555555)

# Concepts Covered

After completing these questions, you should be comfortable with

- ✅ Concatenating DataFrames vertically and horizontally
- ✅ Using `ignore_index`
- ✅ Creating MultiIndex DataFrames using `keys`
- ✅ Using `merge()`
- ✅ Understanding Inner, Left, Right and Outer Join
- ✅ Using `on`, `left_on`, and `right_on`
- ✅ Combining multiple datasets
- ✅ Solving real-world merge problems
- ✅ Performing revenue and enrollment analysis
- ✅ Working confidently with multiple DataFrames in Pandas