# Python Practice Questions - Session 4 (Pandas DataFrame Intermediate)

## Topics Covered

- value_counts()
- sort_values()
- rank()
- sort_index()
- set_index()
- reset_index()
- rename()
- unique()
- nunique()
- isnull()
- notnull()

---

# Dataset

Use the following datasets:

- `movies.csv`
- `ipl-matches.csv`
- `batsman_runs_ipl.csv`
- `diabetes.csv`

You may also create your own DataFrames wherever required.

---

# Instructions

- Solve all questions in Jupyter Notebook.
- Use meaningful variable names.
- Add comments wherever necessary.
- Use only **Pandas** and **NumPy**.
- Test your program with multiple examples.
- Do not modify the original dataset unless explicitly instructed.

# Question 1 — Exploring Unique Values

## Dataset

`ipl-matches.csv`

## Problem Statement

Load the dataset into a DataFrame named `ipl`.

### Requirements

1. Display all unique IPL seasons.
2. Count the total number of unique seasons.
3. Display all unique cities where IPL matches have been played.
4. Count the number of unique venues.
5. Find the number of unique winning teams.
6. Display all unique toss decisions.
7. Count the total number of unique Player of the Match award winners.

### Example Output

```text
Unique Seasons

2008
2009
2010
...

Total Seasons : 15

Unique Toss Decisions

bat
field
```

In [1]:
import numpy as np
import pandas as pd

In [2]:
ipl = pd.read_csv("ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [3]:
ipl['Season'].unique()

<ArrowStringArray>
[   '2022',    '2021', '2020/21',    '2019',    '2018',    '2017',    '2016',
    '2015',    '2014',    '2013',    '2012',    '2011', '2009/10',    '2009',
 '2007/08']
Length: 15, dtype: str

In [4]:
ipl['Season'].nunique()

15

In [5]:
ipl['City'].unique()

<ArrowStringArray>
[     'Ahmedabad',        'Kolkata',         'Mumbai',    'Navi Mumbai',
           'Pune',          'Dubai',        'Sharjah',      'Abu Dhabi',
          'Delhi',        'Chennai',              nan,      'Hyderabad',
  'Visakhapatnam',     'Chandigarh',      'Bengaluru',         'Jaipur',
         'Indore',      'Bangalore',         'Kanpur',         'Rajkot',
         'Raipur',         'Ranchi',        'Cuttack',     'Dharamsala',
          'Kochi',         'Nagpur',   'Johannesburg',      'Centurion',
         'Durban',   'Bloemfontein', 'Port Elizabeth',      'Kimberley',
    'East London',      'Cape Town']
Length: 34, dtype: str

In [6]:
ipl['City'].nunique()

33

In [7]:
ipl['WinningTeam'].nunique()

18

In [8]:
ipl['TossDecision'].unique()

<ArrowStringArray>
['bat', 'field']
Length: 2, dtype: str

In [9]:
ipl['Player_of_Match'].nunique()

262

# Question 2 — Frequency Analysis using value_counts()

## Dataset

`ipl-matches.csv`

## Problem Statement

Load the dataset into a DataFrame named `ipl`.

### Requirements

1. Find how many matches were played in every season.
2. Find how many matches each team has won.
3. Find how many times each toss decision was chosen.
4. Find the frequency of every city.
5. Find the top 10 Player of the Match award winners.

### Example Output

```text
Winner Frequency

Mumbai Indians      131
CSK                 121
KKR                 108
...

Top Player of the Match Winners

AB de Villiers      25
Chris Gayle         22
...
```

In [10]:
ipl['Season'].value_counts()

Season
2013       76
2022       74
2012       74
2011       73
2021       60
2020/21    60
2019       60
2018       60
2016       60
2014       60
2009/10    60
2017       59
2015       59
2007/08    58
2009       57
Name: count, dtype: int64

In [11]:
ipl['WinningTeam'].value_counts()

WinningTeam
Mumbai Indians                 131
Chennai Super Kings            121
Kolkata Knight Riders          114
Royal Challengers Bangalore    109
Rajasthan Royals                96
Kings XI Punjab                 88
Sunrisers Hyderabad             75
Delhi Daredevils                67
Delhi Capitals                  36
Deccan Chargers                 29
Punjab Kings                    13
Gujarat Lions                   13
Gujarat Titans                  12
Pune Warriors                   12
Rising Pune Supergiant          10
Lucknow Super Giants             9
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [12]:
ipl['TossDecision'].value_counts()

TossDecision
field    599
bat      351
Name: count, dtype: int64

In [13]:
ipl['Player_of_Match'].value_counts().head(10)

Player_of_Match
AB de Villiers    25
CH Gayle          22
DA Warner         18
RG Sharma         18
MS Dhoni          17
SR Watson         16
YK Pathan         16
V Kohli           14
KA Pollard        14
SK Raina          14
Name: count, dtype: int64

# Question 3 — Sorting Data

## Dataset

`movies.csv`

## Problem Statement

Load the dataset into a DataFrame named `movies`.

### Requirements

1. Sort the dataset by movie title in ascending order.
2. Sort the dataset by release year in descending order.
3. Sort first by release year (ascending) and then IMDb rating (descending).
4. Sort first by IMDb rating (descending) and then movie title (ascending).
5. Store the sorted DataFrame permanently.

### Example Output

```text
Sorted by Release Year

Title                Year
Movie A              2001
Movie B              2001
Movie C              2002
...
```

In [14]:
movies = pd.read_csv('movies.csv')
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [15]:
movies.sort_values(by='title_x')

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1498,16 December (film),tt0313844,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/16_December_(film),16-Dec,16-Dec,0,2002,158,Action|Thriller,6.9,1091,16 December 1971 was the day when India won t...,Indian intelligence agents race against time t...,NaN,Danny Denzongpa|Gulshan Grover|Milind Soman|Di...,2 nominations,22 March 2002 (India)
1021,1920 (film),tt1301698,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/1920_(film),1920,1920,0,2008,138,Horror|Mystery|Romance,6.4,2588,A devotee of Bhagwan Shri Hanuman Arjun Singh...,After forsaking his family and religion a hus...,A Love Made in Heaven...A Revenge Born in Hell...,Rajniesh Duggall|Adah Sharma|Anjori Alagh|Raj ...,NaN,12 September 2008 (India)
287,1920: London,tt5638500,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/1920_London,1920 London,1920 London,0,2016,120,Horror|Mystery,4.1,1373,Shivangi (Meera Chopra) lives in London with h...,After her husband is possessed by an evil spir...,Fear strikes again,Sharman Joshi|Meera Chopra|Vishal Karwal|Suren...,NaN,6 May 2016 (USA)
723,1920: The Evil Returns,tt2222550,https://upload.wikimedia.org/wikipedia/en/e/e7...,https://en.wikipedia.org/wiki/1920:_The_Evil_R...,1920: Evil Returns,1920: Evil Returns,0,2012,124,Drama|Horror|Romance,4.8,1587,This story revolves around a famous poet who m...,This story revolves around a famous poet who m...,Possession is back,Vicky Ahuja|Tia Bajpai|Irma Jämhammar|Sharad K...,NaN,2 November 2012 (India)
1039,1971 (2007 film),tt0983990,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/1971_(2007_film),1971,1971,0,2007,160,Action|Drama|War,7.9,1121,Based on true facts the film revolves around ...,Based on true facts the film revolves around ...,Honor the heroes.......,Manoj Bajpayee|Ravi Kishan|Deepak Dobriyal|,1 win,9 March 2007 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
778,Zindagi Na Milegi Dobara,tt1562872,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zindagi_Na_Mileg...,Zindagi Na Milegi Dobara,Zindagi Na Milegi Dobara,0,2011,155,Comedy|Drama,8.1,60826,Three friends decide to turn their fantasy vac...,Three friends decide to turn their fantasy vac...,NaN,Hrithik Roshan|Farhan Akhtar|Abhay Deol|Katrin...,30 wins & 22 nominations,15 July 2011 (India)
670,Zindagi Tere Naam,tt2164702,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zindagi_Tere_Naam,Zindagi Tere Naam,Zindagi Tere Naam,0,2012,120,Romance,4.7,27,Mr. Singh an elderly gentleman relates to hi...,Mr. Singh an elderly gentleman relates to hi...,NaN,Mithun Chakraborty|Ranjeeta Kaur|Priyanka Meht...,1 win,16 March 2012 (India)
756,Zokkomon,tt1605790,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zokkomon,Zokkomon,Zokkomon,0,2011,109,Action|Adventure,4.0,274,After the passing of his parents in an acciden...,An orphan is abused and abandoned believed to...,Betrayal. Friendship. Bravery.,Darsheel Safary|Anupam Kher|Manjari Fadnnis|Ti...,NaN,22 April 2011 (India)
939,Zor Lagaa Ke...Haiya!,tt1479857,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zor_Lagaa_Ke...H...,Zor Lagaa Ke... Haiya!,Zor Lagaa Ke... Haiya!,0,2009,\N,Comedy|Drama|Family,6.4,46,A tree narrates the story of four Mumbai-based...,Children build a tree-house to spy on a beggar...,NaN,Meghan Jadhav|Mithun Chakraborty|Riya Sen|Seem...,NaN,NaN
1623,Zubeidaa,tt0255713,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Zubeidaa,Zubeidaa,Zubeidaa,0,2001,153,Biography|Drama|History,6.2,1384,The film begins with Riyaz (Rajat Kapoor) Zub...,Zubeidaa an aspiring Muslim actress marries ...,The Story of a Princess,Karisma Kapoor|Rekha|Manoj Bajpayee|Rajit Kapo...,3 wins & 13 nominations,19 January 2001 (India)

In [16]:
movies.sort_values(by='year_of_release',ascending=False)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
12,Hum Chaar,tt9319812,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Hum_Chaar,Hum chaar,Hum chaar,0,2019,143,Drama,5.6,183,The story of the film revolves around four col...,The story of the film revolves around four col...,NaN,Prit Kamani|Simran Sharma|Anshuman Malhotra|Tu...,NaN,15 February 2019 (India)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
59,Bala (2019 film),tt9420648,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bala_(2019_film),Bala,Bala,0,2019,133,Comedy,8.2,1369,Focuses on a young man Gaurav Rawat aka Bala (...,It tells the story of a man who is balding pre...,NaN,Ayushmann Khurrana|Bhumi Pednekar|Yami Gautam|...,NaN,7 November 2019 (USA)
56,Prassthanam,tt8706884,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Prassthanam,Prassthanam,Prassthanam,0,2019,141,Action|Drama,6.0,272,A rural politician marries a widow with kids a...,A rural politician marries a widow with kids a...,NaN,Sanjay Dutt|Jackie Shroff|Ali Fazal|Manisha Ko...,NaN,20 September 2019 (USA)
57,P Se Pyaar F Se Faraar,tt10816510,https://upload.wikimedia.org/wikipedia/en/7/74...,https://en.wikipedia.org/wiki/P_Se_Pyaar_F_Se_...,P Se Pyaar F Se Faraar,P Se Pyaar F Se Faraar,0,2019,131,Crime|Drama|Romance,7.8,777,In Mathura the ancient city immortalized by t...,High-school sweethearts Suraj Maali and Janvi ...,NaN,Bhavesh Kumar|Jimmy Sheirgill|Kumud Mishra|San...,NaN,18 October 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608,One 2 Ka 4,tt0227194,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/One_2_Ka_4,One 2 Ka 4,One 2 Ka 4,0,2001,169,Action|Comedy|Crime,5.4,4484,Javed Abbas (Jackie Shroff) is a widowed polic...,When a cop's partner is killed in the line of ...,NaN,Shah Rukh Khan|Juhi Chawla|Jackie Shroff|Nirma...,NaN,30 March 2001 (India)
1609,Kyo Kii... Main Jhuth Nahin Bolta,tt0297241,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kyo_Kii_Main_Jhu...,Because I Don't Lie,Kyo Kii... Main Jhuth Nahin Bolta,0,2001,131,Comedy|Fantasy,5.3,1696,"Inspired from the movie ""Liar Liar"" this movi...","Inspired from the movie ""Liar Liar"" this movi...",NaN,Govinda|Sushmita Sen|Rambha|Anupam Kher|Satish...,1 nomination,21 September 2001 (India)
1610,Love Ke Liye Kuch Bhi Karega,tt0287537,https://upload.wikimedia.org/wikipedia/en/e/e0...,https://en.wikipedia.org/wiki/Love_Ke_Liye_Kuc...,Love Ke Liye Kuch Bhi Karega,Love Ke Liye Kuch Bhi Karega,0,2001,131,Comedy|Crime|Romance,6.0,1409,Prakash (Saif Ali Khan) is a handsome gold dig...,Desperate for money three men (Saif Ali Khan ...,NaN,Saif Ali Khan|Fardeen Khan|Aftab Shivdasani|So...,1 win,29 June 2001 (UK)
1611,Pyaar Ishq Aur Mohabbat,tt0285958,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pyaar_Ishq_Aur_M...,Pyaar Ishq Aur Mohabbat,Pyaar Ishq Aur Mohabbat,0,2001,\N,Drama|Musical|Romance,4.0,528,Young and beautiful Isha Nair has three admire...,Young and beautiful Isha Nair has three admire...,NaN,Arjun Rampal|Kirti Reddy|Sunil Shetty|Aftab Sh...,1 win,26 September 2001 (Kuwait)
1612,Pyaar Tune Kya Kiya,tt0281102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pyaar_Tune_Kya_Kiya,Pyaar Tune Kya Kiya...,Pyaar Tune Kya Kiya...,0,2001,123,Romance|Thriller,5.7,719,Ria Jaiswal lives a very wealthy lifestyle alo...,A obsessive woman determines to do what it tak...,NaN,Fardeen Khan|,8 nominations,27 April 2001 (India)

In [17]:
movies.sort_values(by=['year_of_release','imdb_rating'],ascending=[True,False])

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1567,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1568,Lagaan,tt0169102,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Lagaan:_Once_Upo...,Lagaan: Once Upon a Time in India,Lagaan: Once Upon a Time in India,0,2001,224,Adventure|Drama|Musical,8.1,95686,This is the story about the resilience shown b...,The people of a small village in Victorian Ind...,Once upon a time in India,Aamir Khan|Gracy Singh|Rachel Shelley|Paul Bla...,Nominated for 1 Oscar,15 June 2001 (USA)
1571,Dil Chahta Hai,tt0292490,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dil_Chahta_Hai,Dil Chahta Hai,Dil Chahta Hai,0,2001,183,Comedy|Drama|Romance,8.1,62313,Three young men Akash Sameer and Siddharth a...,Three inseparable childhood friends are just o...,Welcome to a summer of their lives you will ne...,Aamir Khan|Saif Ali Khan|Akshaye Khanna|Preity...,22 wins & 37 nominations,10 August 2001 (India)
1607,Nayak (2001 Hindi film),tt0291376,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Nayak_(2001_Hind...,Nayak: The Real Hero,Nayak: The Real Hero,0,2001,187,Action|Drama|Thriller,7.8,12522,Employed as a camera-man at a popular televisi...,A man accepts a challenge by the chief ministe...,Fight the power,Anil Kapoor|Rani Mukerji|Amrish Puri|Johnny Le...,2 nominations,7 September 2001 (India)
1589,Chandni Bar,tt0267363,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chandni_Bar,Chandni Bar,Chandni Bar,0,2001,150,Crime|Drama,7.6,2284,Mumtaz is a village girl whose family is kille...,A displaced woman is forced to become a beer-b...,NaN,Tabu|Atul Kulkarni|Rajpal Yadav|Shri Vallabh V...,7 wins & 14 nominations,28 September 2001 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Pagalpanti (2019 film),tt9495690,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Pagalpanti_(2019...,Pagalpanti (Hindi),Pagalpanti,0,2019,149,Action|Comedy,3.1,2100,A tourist group from India sets out on a vacat...,A tourist group from India sets out on a vacat...,NaN,Kriti Kharbanda|John Abraham|Ileana D'Cruz|Ani...,NaN,NaN
78,Dabangg 3,tt7059844,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dabangg_3,Dabangg 3,Dabangg 3,0,2019,160,Action,3.0,15000,Third installment of the Dabanng film series.,Third installment of the Dabanng film series.,NaN,Salman Khan|Sonakshi Sinha|Sudeep|Mahesh Manjr...,NaN,NaN
10,Amavas,tt8396186,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Amavas,Amavas,Amavas,0,2019,134,Horror|Thriller,2.8,235,Far away from the bustle of the city a young ...,The lives of a couple turn into a nightmare a...,NaN,Ali Asgar|Vivan Bhatena|Nargis Fakhri|Sachiin ...,NaN,8 February 2019 (India)
30,Student of the Year 2,tt7255568,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Student_of_the_Y...,Student of the Year 2,Student of the Year 2,0,2019,146,Drama|Romance|Sport,2.5,12671,A student must face off against bullies and ov...,A student must face off against bullies and ov...,NaN,Tiger Shroff|Ananya Panday|Tara Sutaria|Aditya...,NaN,10 May 2019 (USA)
70,Keep Safe Distance (film),tt8876008,NaN,https://en.wikipedia.org/wiki/Keep_Safe_Distan...,Keep Safe Distance,Keep Safe Distance,0,2019,128,Action|Thriller,0.0,0,Keep Safe Distance is an upcoming Indian thril...,Keep Safe Distance is an upcoming Indian thril...,NaN,Shahbaaz Khan|Adi Irani|Vikas Anand|Kiran Kuma...,NaN,NaN

In [18]:
movies.sort_values(by=['imdb_rating','title_x'],ascending=[False,True])

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,NaN,19 July 2019 (India)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)
62,Saand Ki Aankh,tt8108206,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Saand_Ki_Aankh,Saand Ki Aankh,Saand Ki Aankh,0,2019,146,Biography|Drama,8.9,1902,Both over the age of 60 Chandro Tomar and Pra...,Both over the age of 60 Chandro Tomar and Pra...,NaN,Taapsee Pannu|Bhumi Pednekar|Prakash Jha|Viine...,1 nomination,25 October 2019 (USA)
1435,Final Solution (2003 film),tt0402178,NaN,https://en.wikipedia.org/wiki/Final_Solution_(...,Final Solution,Final Solution,0,2004,218,Documentary,8.7,333,The Final Solution is a 2003 documentary direc...,The Final Solution is a 2003 documentary direc...,NaN,NaN,5 wins & 2 nominations,13 February 2004 (Germany)
58,Ghost (2019 film),tt9378950,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ghost_(2019_film),Ghost,Ghost,0,2019,130,Horror|Thriller,8.7,1379,The story of the film follows Karan Khanna a ...,The story of the film follows Karan Khanna a ...,NaN,Sanaya Irani|Shivam Bhaargava|Vikram Bhatt|Ame...,NaN,18 October 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,Ek Kahani Julie Ki,tt7997334,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ek_Kahani_Julie_Ki,Ek Kahani Julie Ki,Ek Kahani Julie Ki,0,2016,119,Drama,0.0,0,NaN,Add a Plot »,NaN,Jimmy Sharma|,NaN,NaN
186,Ek Thi Rani Aisi Bhi,tt6752836,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ek_Thi_Rani_Aisi...,Ek Rani Aisi Bhi Thi,Ek Rani Aisi Bhi Thi,0,2013,\N,Biography|History,0.0,0,Simple but yet elegant Rajmata and her journey...,Simple but yet elegant Rajmata and her journey...,NaN,Hema Malini|Vinod Khanna|Sachin Khedekar|Rajes...,NaN,NaN
407,I Love Desi,tt4718678,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/I_Love_Desi,I Love Desi,I Love Desi,0,2015,\N,Comedy|Romance,0.0,0,NaN,Add a Plot »,NaN,Shakti Anand|Arun Bali|Vedant Bali|Sunita Dhir...,NaN,NaN
70,Keep Safe Distance (film),tt8876008,NaN,https://en.wikipedia.org/wiki/Keep_Safe_Distan...,Keep Safe Distance,Keep Safe Distance,0,2019,128,Action|Thriller,0.0,0,Keep Safe Distance is an upcoming Indian thril...,Keep Safe Distance is an upcoming Indian thril...,NaN,Shahbaaz Khan|Adi Irani|Vikas Anand|Kiran Kuma...,NaN,NaN
298,Khel Toh Ab Shuru Hoga,tt6656806,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Khel_Toh_Ab_Shur...,khel toh ab shuru hoga,khel toh ab shuru hoga,0,2016,130,Action|Thriller,0.0,0,A bank security guard Abbas (Ruslaan) ploys to...,A bank security guard Abbas (Ruslaan) ploys to...,NaN,Hazel Croney|Devshi Khanduri|Ruslaan Mumtaz|,NaN,13 May 2016 (India)

In [19]:
movies.sort_values(by=['imdb_rating','title_x'],ascending=[False,True],inplace=True)

In [20]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
41,Family of Thakurganj,tt8897986,https://upload.wikimedia.org/wikipedia/en/9/99...,https://en.wikipedia.org/wiki/Family_of_Thakur...,Family of Thakurganj,Family of Thakurganj,0,2019,127,Action|Drama,9.4,895,The film is based on small town of North India...,The film is based on small town of North India...,NaN,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...,NaN,19 July 2019 (India)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)
62,Saand Ki Aankh,tt8108206,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Saand_Ki_Aankh,Saand Ki Aankh,Saand Ki Aankh,0,2019,146,Biography|Drama,8.9,1902,Both over the age of 60 Chandro Tomar and Pra...,Both over the age of 60 Chandro Tomar and Pra...,NaN,Taapsee Pannu|Bhumi Pednekar|Prakash Jha|Viine...,1 nomination,25 October 2019 (USA)
1435,Final Solution (2003 film),tt0402178,NaN,https://en.wikipedia.org/wiki/Final_Solution_(...,Final Solution,Final Solution,0,2004,218,Documentary,8.7,333,The Final Solution is a 2003 documentary direc...,The Final Solution is a 2003 documentary direc...,NaN,NaN,5 wins & 2 nominations,13 February 2004 (Germany)
58,Ghost (2019 film),tt9378950,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ghost_(2019_film),Ghost,Ghost,0,2019,130,Horror|Thriller,8.7,1379,The story of the film follows Karan Khanna a ...,The story of the film follows Karan Khanna a ...,NaN,Sanaya Irani|Shivam Bhaargava|Vikram Bhatt|Ame...,NaN,18 October 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,Ek Kahani Julie Ki,tt7997334,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ek_Kahani_Julie_Ki,Ek Kahani Julie Ki,Ek Kahani Julie Ki,0,2016,119,Drama,0.0,0,NaN,Add a Plot »,NaN,Jimmy Sharma|,NaN,NaN
186,Ek Thi Rani Aisi Bhi,tt6752836,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ek_Thi_Rani_Aisi...,Ek Rani Aisi Bhi Thi,Ek Rani Aisi Bhi Thi,0,2013,\N,Biography|History,0.0,0,Simple but yet elegant Rajmata and her journey...,Simple but yet elegant Rajmata and her journey...,NaN,Hema Malini|Vinod Khanna|Sachin Khedekar|Rajes...,NaN,NaN
407,I Love Desi,tt4718678,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/I_Love_Desi,I Love Desi,I Love Desi,0,2015,\N,Comedy|Romance,0.0,0,NaN,Add a Plot »,NaN,Shakti Anand|Arun Bali|Vedant Bali|Sunita Dhir...,NaN,NaN
70,Keep Safe Distance (film),tt8876008,NaN,https://en.wikipedia.org/wiki/Keep_Safe_Distan...,Keep Safe Distance,Keep Safe Distance,0,2019,128,Action|Thriller,0.0,0,Keep Safe Distance is an upcoming Indian thril...,Keep Safe Distance is an upcoming Indian thril...,NaN,Shahbaaz Khan|Adi Irani|Vikas Anand|Kiran Kuma...,NaN,NaN
298,Khel Toh Ab Shuru Hoga,tt6656806,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Khel_Toh_Ab_Shur...,khel toh ab shuru hoga,khel toh ab shuru hoga,0,2016,130,Action|Thriller,0.0,0,A bank security guard Abbas (Ruslaan) ploys to...,A bank security guard Abbas (Ruslaan) ploys to...,NaN,Hazel Croney|Devshi Khanduri|Ruslaan Mumtaz|,NaN,13 May 2016 (India)

# Question 4 — Ranking Players

## Dataset

`batsman_runs_ipl.csv`

## Problem Statement

Load the dataset into a DataFrame named `batsman`.

### Requirements

1. Create a new column named `Batting Rank`.
2. The batsman with the highest runs should receive Rank 1.
3. Display the top 20 ranked batsmen.
4. Display the bottom 20 ranked batsmen.
5. Find Virat Kohli's batting rank.
6. Find all players having Rank less than or equal to 10.

### Example Output

```text
Top Ranked Players

Rank    Batsman
1       Virat Kohli
2       Shikhar Dhawan
3       Rohit Sharma
...
```

In [21]:
batsman = pd.read_csv("batsman_runs_ipl.csv")
batsman

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [22]:
batsman['Batting Rank'] = batsman['batsman_run'].rank(ascending=False, method='min').astype(int)
batsman

             batter  batsman_run  Batting Rank
0    A Ashish Reddy          280           166
1          A Badoni          161           225
2        A Chandila            4           529
3          A Chopra           53           328
4       A Choudhary           25           402
..              ...          ...           ...
600      Yash Dayal            0           583
601   Yashpal Singh           47           343
602     Younis Khan            3           542
603    Yuvraj Singh         2754            27
604          Z Khan          117           255

[605 rows x 3 columns]

In [23]:
batsman.sort_values(by='Batting Rank')

             batter  batsman_run  Batting Rank
569         V Kohli         6634             1
462        S Dhawan         6244             2
130       DA Warner         5883             3
430       RG Sharma         5881             4
493        SK Raina         5536             5
..              ...          ...           ...
570  V Pratap Singh            0           583
63     Abdur Razzak            0           583
562          U Kaul            0           583
65       Akash Deep            0           583
57           AS Roy            0           583

[605 rows x 3 columns]

In [24]:
batsman.sort_values(by='Batting Rank').head(20)

             batter  batsman_run  Batting Rank
569         V Kohli         6634             1
462        S Dhawan         6244             2
130       DA Warner         5883             3
430       RG Sharma         5881             4
493        SK Raina         5536             5
27   AB de Villiers         5181             6
108        CH Gayle         4997             7
339        MS Dhoni         4978             8
452      RV Uthappa         4954             9
256      KD Karthik         4377            10
174       G Gambhir         4217            11
60        AT Rayudu         4190            12
46        AM Rahane         4074            13
263        KL Rahul         3895            14
511       SR Watson         3880            15
328       MK Pandey         3657            16
519       SV Samson         3526            17
251      KA Pollard         3437            18
169    F du Plessis         3403            19
597       YK Pathan         3222            20

In [25]:
batsman.sort_values(by='Batting Rank').tail(20)

             batter  batsman_run  Batting Rank
466       S Kaushik            0           583
230        JL Denly            0           583
600      Yash Dayal            0           583
415  R Sanjay Yadav            0           583
595      YA Abdulla            0           583
593   Y Prithvi Raj            0           583
438     RP Meredith            0           583
360        ND Doshi            0           583
440      RR Bhatkal            0           583
468    S Lamichhane            0           583
467         S Ladda            0           583
512     SS Cottrell            0           583
203       IC Pandey            0           583
537     Sunny Gupta            0           583
102         C Nanda            0           583
570  V Pratap Singh            0           583
63     Abdur Razzak            0           583
562          U Kaul            0           583
65       Akash Deep            0           583
57           AS Roy            0           583

In [26]:
batsman[batsman['batter'] == 'V Kohli']

      batter  batsman_run  Batting Rank
569  V Kohli         6634             1

In [27]:
batsman[batsman['Batting Rank'] <= 10]

             batter  batsman_run  Batting Rank
27   AB de Villiers         5181             6
108        CH Gayle         4997             7
130       DA Warner         5883             3
256      KD Karthik         4377            10
339        MS Dhoni         4978             8
430       RG Sharma         5881             4
452      RV Uthappa         4954             9
462        S Dhawan         6244             2
493        SK Raina         5536             5
569         V Kohli         6634             1

# Question 5 — Index Operations and Missing Value Analysis

## Dataset

`diabetes.csv`

## Problem Statement

Load the dataset into a DataFrame named `diabetes`.

### Part A — Index Operations

1. Set the first column as the DataFrame index.
2. Display the DataFrame.
3. Reset the index back to default.
4. Rename any three columns with meaningful names.
5. Display the updated column names.

---

### Part B — Missing Value Analysis

1. Count missing values in every column.
2. Count non-missing values in every column.
3. Display only the columns containing missing values.
4. Find the column having the highest number of missing values.
5. Display whether the DataFrame contains any missing values.

### Example Output

```text
Missing Values

Glucose        5
BloodPressure  3
BMI            7

Column with Maximum Missing Values

BMI
```

In [28]:
diabetes = pd.read_csv('diabetes.csv')
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [29]:
diabetes = diabetes.set_index('Pregnancies')
diabetes

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,,,,,,,,
6,148,72,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
8,183,64,0,0,23.3,0.672,32,1
1,89,66,23,94,28.1,0.167,21,0
0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
10,101,76,48,180,32.9,0.171,63,0
2,122,70,27,0,36.8,0.340,27,0
5,121,72,23,112,26.2,0.245,30,0
1,126,60,0,0,30.1,0.349,47,1
1,93,70,31,0,30.4,0.315,23,0

In [30]:
diabetes = diabetes.reset_index()
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [31]:
diabetes = diabetes.rename(columns={
    'Glucose': 'Blood_Sugar_Level', 
    'BloodPressure': 'Blood_Pressure_mmHg', 
    'SkinThickness': 'Skin_Fold_Thickness'
})
diabetes

,Pregnancies,Blood_Sugar_Level,Blood_Pressure_mmHg,Skin_Fold_Thickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [32]:
diabetes.isnull().sum()

Pregnancies                 0
Blood_Sugar_Level           0
Blood_Pressure_mmHg         0
Skin_Fold_Thickness         0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [33]:
diabetes.notnull().sum()

Pregnancies                 768
Blood_Sugar_Level           768
Blood_Pressure_mmHg         768
Skin_Fold_Thickness         768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [34]:
diabetes[diabetes.isna()].sum()

Pregnancies                 0.0
Blood_Sugar_Level           0.0
Blood_Pressure_mmHg         0.0
Skin_Fold_Thickness         0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
Outcome                     0.0
dtype: float64

# Concepts Covered

After completing these questions, you should be comfortable with

- ✅ Finding unique values
- ✅ Counting frequencies using `value_counts()`
- ✅ Sorting DataFrames
- ✅ Ranking data using `rank()`
- ✅ Working with indexes
- ✅ Setting and resetting indexes
- ✅ Renaming columns
- ✅ Detecting missing values
- ✅ Performing basic exploratory data analysis (EDA)
- ✅ Working with real-world datasets